import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {once} from 'node:events';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {createGameServer} from '../server/service';import {MemoryStore} from '../server/store';import {createRace,crashRider} from '../src/game/simulation';import {freshSave,SAVE_KEY} from '../src/game/save';import {getTrack} from '../src/game/content';
const published=!!process.env.PUBLIC_URL,base=process.env.PUBLIC_URL||'http://127.0.0.1:4392/',folder=process.env.QA_DIR||'output/falls-integration/solo';await fs.mkdir(folder,{recursive:true});
const app=published?null:createGameServer(new MemoryStore());if(app){app.server.listen(0,'127.0.0.1');await once(app.server,'listening');}
const vite=app?spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','4392','--strictPort'],{env:{...process.env,ASFALTO_SERVER_URL:`http://127.0.0.1:${(app.server.address() as any).port}`},stdio:'ignore'}):null;
if(vite)for(let i=0;i<100;i++){try{if((await fetch(base)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:800}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});if(!published)await page.route('**/api/visitors*',r=>r.fulfill({json:{visitors:0}}));
const seed={...freshSave(),cash:12000,races:1,unlocked:4,ownedKneePads:['gold'],kneePadId:'gold'};
await page.addInitScript(({key,save})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(save));sessionStorage.setItem('asfalto-instructions','1');},{key:SAVE_KEY,save:seed});
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));const step=(frames:number)=>page.evaluate(n=>{for(let i=0;i<n;i++)window.advanceTime(1000/60);},frames);
const shot=async(n:string)=>{await page.screenshot({path:`${folder}/${n}.png`});await fs.writeFile(`${folder}/${n}.json`,JSON.stringify(await state(),null,2));};
function fixture(kind:'impact'|'spill',zero=false,rain=false){const s=createRace('costa',seed,712,rain?'rain':'day');s.mode='racing';s.time=12;s.tick=720;s.countdown=0;s.traffic=[];s.obstacles=[];s.riders.forEach((r,i)=>Object.assign(r,{x:1.5,z:600+i*110,speed:i?20:45,immune:0,integrity:zero&&!i?10:100}));crashRider(s,s.riders[0],true,kind);return s;}
async function restore(s:any){await page.evaluate(s=>window.__game!.restore(JSON.stringify(s)),s);}
async function pickup(){for(let i=0;i<100&&(await state()).player.recovery;i++){const p=(await state()).player;if(p.recovery.phase==='exploding')break;const dx=p.recovery.bikeX-p.x,dz=p.recovery.bikeZ-p.z,n=Math.max(1,Math.hypot(dx,dz));await page.evaluate(({dx,dz,n})=>window.__game!.command({throttle:Math.max(0,dz/n),brake:Math.max(0,-dz/n),steer:dx/n,attack:null},12),{dx,dz,n});}}
try{
 await page.goto(base+'?test');await page.waitForFunction(()=>!!window.__game);assert.equal(await page.locator('#prototype-toggle').count(),0);assert.ok(await page.locator('#online-btn').isVisible());await page.click('#ranking-btn');assert.equal(await page.locator('#rank-rules option').count(),3);await page.selectOption('#rank-rules','2');await shot('ranking-history');await page.keyboard.press('Escape');
 for(const [kind,key] of [['impact','ArrowDown'],['spill','ArrowUp']] as const){await restore(fixture(kind,false,true));const held=(await state()).camera;await step(30);await shot(`${kind}-rain-slide`);await step(300);assert.deepEqual((await state()).camera,held);const initial=(await state()).player.z;await page.keyboard.down(key);await step(30);await page.keyboard.up(key);assert.equal((await state()).player.z<initial,kind==='impact');await pickup();assert.equal((await state()).player.recovery,null);assert.equal((await state()).result,null);}
 await restore(fixture('impact',true));await step(300);assert.equal((await state()).result,null);await pickup();assert.equal((await state()).player.recovery.phase,'exploding');await shot('explosion');await step(130);assert.equal((await state()).result.reason,'wrecked');assert.match(await page.locator('#result-title').innerText(),/EXPLODIU/);await page.click('#result-menu-btn');
 await page.click('#championship-btn');await page.click('#champ-start');const champ=await page.evaluate(()=>JSON.parse(window.__game!.snapshot()));champ.mode='racing';champ.time=12;champ.tick=720;Object.assign(champ.riders[0],{x:1.5,z:600,speed:45,integrity:10});champ.traffic=[];champ.obstacles=[];crashRider(champ,champ.riders[0],true,'impact');await restore(champ);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await page.reload();await page.click('#championship-btn');assert.ok(await page.locator('#champ-start').isEnabled());assert.equal(await page.locator('#champ-repair').count(),0);await page.click('#champ-start');assert.equal((await state()).player.integrity,0);assert.equal((await state()).player.recovery.phase,'sliding');await shot('championship-resumed-zero');await page.click('#pause-btn');await page.click('#menu-btn');await page.waitForFunction(()=>!JSON.parse(window.render_game_to_text()).championship.settling);await page.click('#champ-menu');
 // Actual wet-knee activation through two distinct input events.
 const wet=fixture('spill',false,true);delete wet.riders[0].recovery;Object.assign(wet.riders[0],{x:-4,z:735,speed:45,crash:0,falls:0,integrity:100,kneeTime:0,wetKneeTicks:0});await restore(wet);await page.setViewportSize({width:390,height:844});await page.keyboard.press('ArrowRight');await page.keyboard.down('ArrowRight');await step(65);assert.ok((await state()).player.wetKneeTime>1);assert.equal((await state()).player.falls,0);await shot('mobile-knee');await step(65);await page.keyboard.up('ArrowRight');assert.equal((await state()).player.falls,1);await shot('mobile-fall');await step(300);await pickup();assert.equal((await state()).player.recovery,null);
 // Normal finish and next-route navigation still work with the new camera controller.
 const finish=createRace('costa',seed,7,'day');finish.mode='racing';finish.time=150;finish.tick=9000;finish.traffic=[];finish.obstacles=[];finish.riders.forEach((r,i)=>Object.assign(r,{x:i?2:0,z:getTrack('costa').distance-2-i*20,speed:40,immune:10}));await restore(finish);await step(10);assert.equal((await state()).result.reason,'finish');await step(320);await shot('finish');await page.click('#next-race-btn');assert.equal((await state()).condition,'sunset');
 assert.deepEqual(errors,[]);console.log('Solo passed: rain slide/camera, both walking directions, explosion, zero-integrity championship reload, mobile knee fall, historic rankings, finish and next route.');
}catch(error){await shot('failure');console.log('Diagnostic',JSON.stringify(await state()));throw error;}finally{await fs.writeFile(`${folder}/errors.json`,JSON.stringify(errors));await browser.close();vite?.kill('SIGTERM');await app?.close();}
