import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';

const source=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const target=process.argv[2];
if(!target)throw new Error('Informe a pasta do catálogo Jogos ou de um worktree dele.');
const destination=path.resolve(target);
await fs.access(path.join(destination,'index.html'));await fs.access(path.join(destination,'package.json'));
execFileSync('npm',['run','build'],{cwd:source,stdio:'inherit'});
const game=path.join(destination,'games','asfalto-bruto');
await fs.mkdir(game,{recursive:true});
for(const file of ['assets','fonts','index.html','favicon.svg','privacidade.html']) {
  await fs.rm(path.join(game,file),{recursive:true,force:true});await fs.cp(path.join(source,'dist',file),path.join(game,file),{recursive:true});
}
await build({entryPoints:[path.join(source,'api/asfalto.ts')],outfile:path.join(destination,'api/asfalto.js'),bundle:true,platform:'node',target:'node22',format:'cjs',external:['ws','ioredis'],footer:{js:'module.exports = module.exports.default;'},banner:{js:'// Generated by sources/asfalto-bruto/scripts/export-jogos.mjs. Do not edit this bundle directly.'}});
const sources=path.join(destination,'sources','asfalto-bruto');await fs.mkdir(sources,{recursive:true});
for(const file of ['src','server','api','scripts','tests','docs','public','package.json','package-lock.json','tsconfig.json','vite.config.ts','index.html','README.md','MULTIPLAYER.md','.gitignore']) {
  await fs.rm(path.join(sources,file),{recursive:true,force:true});await fs.cp(path.join(source,file),path.join(sources,file),{recursive:true});
}
const pkgPath=path.join(destination,'package.json'),pkg=JSON.parse(await fs.readFile(pkgPath,'utf8'));
const local=JSON.parse(await fs.readFile(path.join(source,'package.json'),'utf8'));
pkg.dependencies={...pkg.dependencies,ws:local.dependencies.ws,ioredis:local.dependencies.ioredis,jose:local.dependencies.jose};await fs.writeFile(pkgPath,JSON.stringify(pkg,null,2)+'\n');
const configPath=path.join(destination,'vercel.json'),config=JSON.parse(await fs.readFile(configPath,'utf8'));
// Production is hosted on our VPS; exporting/pushing must not trigger legacy Vercel builds.
config.git={...config.git,deploymentEnabled:false};
config.functions={...config.functions,'api/asfalto.js':{maxDuration:300,regions:['gru1']}};await fs.writeFile(configPath,JSON.stringify(config,null,2)+'\n');
const ignores=path.join(destination,'.vercelignore');const ignore=await fs.readFile(ignores,'utf8');if(!ignore.includes('sources/asfalto-bruto'))await fs.appendFile(ignores,'\nsources/asfalto-bruto\n');
const catalogPath=path.join(destination,'index.html');let catalog=await fs.readFile(catalogPath,'utf8');
if(!catalog.includes('/games/asfalto-bruto/'))catalog=catalog.replace('<section class="grid">',`<section class="grid">\n        <a class="card" href="/games/asfalto-bruto/">\n          <h2>Asfalto Bruto</h2>\n          <p>Corrida e combate de motos. Jogue sozinho ou crie uma sala online para 2 a 8 pessoas.</p>\n          <span class="pill">Corrida · Multiplayer</span>\n        </a>\n`);
await fs.writeFile(catalogPath,catalog);
console.log(`Asfalto Bruto integrado em ${game}`);
