import { CHAMP_POINTS, championshipBikeState, championshipGarageOpen, championshipPoints, championshipRoute, championshipStandings, type Championship } from './game/championship';
import { TRACKS, getBike, money } from './game/content';
import { CONDITIONS } from './game/conditions';
import type { SaveData } from './game/types';
import { repairCost } from './game/save';
import { raceOutcome } from './game/race-outcome';
const names=['Dia','Entardecer','Noite','Chuva'];
export function championshipMarkup(c:Championship|undefined,save:SaveData,payout?:number){
 const track=TRACKS[c?.stage ?? 0],done=c?.heats.length===4,rows=championshipStandings(c?.heats ?? []),me=rows.find(r=>r.id==='player')!;
 const title=!c?'Campeonato':c.status==='eliminated'?'Fim do campeonato':c.status==='complete'?(me.rank===1?'Campeão do asfalto':'Campeonato concluído'):c.status==='service'?'Etapa conquistada':track.name;
 const explanation=!c?'Cinco estradas. Quatro corridas em cada uma. Termine cada etapa entre os três primeiros para seguir adiante.':c.status==='eliminated'?`Você terminou a etapa em ${me.rank}º. Para tentar novamente, comece pela Costa do Sol.`:c.status==='complete'?`Você atravessou as cinco etapas e terminou a final em ${me.rank}º.`:done?`Você ficou em ${me.rank}º e avançou. Agora pode visitar a garagem antes de seguir para ${TRACKS[c.stage+1].name}.`:'A classificação soma as quatro corridas desta etapa. Os três primeiros avançam; os pontos recomeçam na próxima estrada.';
 const last=c?.heats.at(-1),result=last?.finishes.find(r=>r.id==='player');
 const outcome=last&&last.reason!=='finish'?raceOutcome(last.reason,last):null;
 const next=c?championshipRoute(c):{track:TRACKS[0],condition:CONDITIONS[0]};
 const canGarage=!c||championshipGarageOpen(c),bikeState=championshipBikeState(save,c),{bikeId:bike,integrity,locked}=bikeState;
 const percent=integrity>0?Math.max(1,Math.floor(integrity)):0,cost=repairCost(save,bike,integrity),canAfford=save.cash>=cost;
 return `<div class="dialog-header"><div><div class="eyebrow">CAMPEONATO · ETAPA ${(c?.stage ?? 0)+1} / ${TRACKS.length}</div><h2>${title}</h2></div><button class="close-btn" id="champ-close" aria-label="Voltar ao menu">×</button></div><div class="dialog-body champ-body">
 <ol class="champ-stages" aria-label="Etapas do campeonato">${TRACKS.map((t,i)=>`<li class="${i===(c?.stage ?? 0)?'current':i<(c?.stage ?? 0)?'passed':''}"><span>${i<(c?.stage ?? 0)?'✓':i+1}</span>${t.name}</li>`).join('')}</ol>
 <p class="champ-explanation">${explanation}</p>
 ${outcome?`<div class="race-outcome" role="status"><strong>${outcome.label} · 0 PONTOS NESTA CORRIDA</strong><p>${outcome.description}</p></div>`:''}
 ${bikeState.low?`<div class="champ-integrity-alert ${bikeState.blocked?'broken':''}" role="alert"><strong>${bikeState.blocked?'MOTO EM 0% · LARGADA BLOQUEADA':`ATENÇÃO · MOTO COM ${percent}% DE INTEGRIDADE`}</strong><span>${bikeState.blocked?'Não pode iniciar a corrida. Arrume a moto para continuar.':bikeState.recovering?'Retome para continuar buscando a moto. Se estiver em 0%, ela explode ao tentar pegá-la.':locked?'A moto está abaixo de 20% e pode quebrar na próxima corrida. Dentro da etapa, o reparo só libera se chegar a 0%.':'A moto está abaixo de 20%. Recomendamos reparar na garagem antes de iniciar a corrida.'}</span>${bikeState.canRepair&&!canAfford?`<small>Faltam ${money(cost-save.cash)} para o reparo. Você pode ganhar créditos nas corridas livres.</small>`:''}${bikeState.canRepair?`<button class="primary" id="champ-repair" ${canAfford?'':'disabled'}>REPARAR MOTO · ${money(cost)}</button>`:''}</div>`:''}
 <div class="champ-rules">${CHAMP_POINTS.map((pts,i)=>`<span>${i+1}º <b>${pts}</b></span>`).join('')}<small>PONTOS POR CORRIDA</small></div>
 ${c?`<div class="champ-board-title"><h3>${track.name}</h3><span>${c.heats.length} / 4 CORRIDAS</span></div><div class="champ-table-wrap"><table class="champ-table"><thead><tr><th>PILOTO</th>${names.map((n,i)=>`<th aria-label="${n}" title="${n}">${['DIA','ENT.','NOITE','CHUVA'][i]}</th>`).join('')}<th>TOTAL</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.id==='player'?'me':''} ${r.rank<=3?'qualified':''}"><th><span>${c.heats.length?r.rank:'—'}</span> ${r.name}${c.heats.length&&r.rank===3?'<i title="Limite de classificação">▲</i>':''}</th>${names.map((_,i)=>`<td title="${r.finishes[i]?r.finishes[i].place===null?'Não terminou':`${r.finishes[i].place}º lugar`: 'A disputar'}">${r.rounds[i] ?? '—'}</td>`).join('')}<td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></div><p class="champ-tiebreak">Desempate: melhores colocações, menor tempo total e ordem inicial de largada. Quem não termina marca zero.</p>`:`<div class="champ-intro"><b>DIA → ENTARDECER → NOITE → CHUVA</b><p>Os danos da moto continuam de uma corrida para a outra. Troca de equipamento e reparos ficam entre as etapas de quatro corridas. Se a moto quebrar e chegar a 0%, pode consertar também dentro da etapa. Os rivais também carregam os danos.</p><p>Se não passar da etapa, o campeonato recomeça na Costa do Sol. Sua garagem e seus créditos continuam com você.</p></div>`}
 ${result?`<div class="champ-last"><b>${result.place===null?'NÃO TERMINOU':`${result.place}º NA ÚLTIMA CORRIDA`} · +${championshipPoints(result.place)} PONTOS</b>${payout!==undefined?`<span>+ ${money(payout)} EM CRÉDITOS</span>`:''}</div>`:''}
 <div class="champ-bike"><span>${getBike(bike).name} <b>${percent}%</b></span><small>${locked?bikeState.canRepair?'MOTO QUEBRADA · REPARO LIBERADO':'REPAROS SÓ ENTRE ETAPAS OU COM A MOTO EM 0%':'GARAGEM LIBERADA'}</small></div>
 <div class="champ-actions">${!c||!['eliminated','complete'].includes(c.status)?`<button class="primary" id="champ-start" ${bikeState.blocked?'disabled':''}>${c?.status==='racing'?'RETOMAR CORRIDA':c?.status==='service'?`PRÓXIMA ETAPA · ${TRACKS[c.stage+1].name.toUpperCase()}`:c?.heats.length?`PRÓXIMA CORRIDA · ${next.condition.name.toUpperCase()}`:`INICIAR · ${next.track.name.toUpperCase()} ${next.condition.name.toUpperCase()}`} ↗</button>`:`<button class="primary" id="champ-restart">COMEÇAR DE NOVO ↗</button>`}${canGarage?'<button class="secondary" id="champ-garage">GARAGEM · REPAROS & EQUIPAMENTOS</button>':''}<button class="secondary" id="champ-menu">VOLTAR AO MENU</button>${c&&!['eliminated','complete'].includes(c.status)?'<button class="text-button danger" id="champ-restart">RECOMEÇAR CAMPEONATO DO ZERO</button>':''}</div></div>`;
}
