// Generated by sources/asfalto-bruto/scripts/export-jogos.mjs. Do not edit this bundle directly.
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api/asfalto.ts
var asfalto_exports = {};
__export(asfalto_exports, {
  default: () => asfalto_default
});
module.exports = __toCommonJS(asfalto_exports);
var import_node_http2 = require("node:http");

// server/service.ts
var import_node_http = require("node:http");
var import_node_crypto2 = require("node:crypto");
var import_ws = require("ws");

// src/game/content.ts
var BIKES = [
  { id: "ferro", name: "Ferro 500", class: "STREET", price: 0, speed: 64, acceleration: 13.2, handling: 1.1, armor: 1, color: "#dfff71", tagline: "Leve, esperta e pronta pra briga." },
  { id: "veneno", name: "Veneno 750", class: "SPORT", price: 2800, speed: 73, acceleration: 15, handling: 1.2, armor: 0.95, color: "#ee734d", tagline: "A reta \xE9 sua. O resto voc\xEA conquista." },
  { id: "brutal", name: "Brutal 1000", class: "MUSCLE", price: 4800, speed: 78, acceleration: 12.5, handling: 0.95, armor: 1.4, color: "#b6a1fb", tagline: "Mais motor. Menos conversa." }
];
var TRACKS = [
  { id: "costa", name: "Costa do Sol", region: "RODOVIA LITOR\xC2NEA", distance: 8400, difficulty: "NORMAL", prize: 1400, index: 0, sky: ["#567d9b", "#e0a6aa", "#fbd4ad"], land: ["#779b77", "#699271"], road: ["#555a5b", "#505557"], accent: "#deff70" },
  { id: "serra", name: "Serra da Fuma\xE7a", region: "ESTRADA DA MONTANHA", distance: 9200, difficulty: "DIF\xCDCIL", prize: 1850, index: 1, sky: ["#555f83", "#b794b1", "#f2c2b5"], land: ["#728b70", "#637e67"], road: ["#555962", "#50545c"], accent: "#b9a0f8" },
  { id: "deserto", name: "Vale Vermelho", region: "FRONTEIRA DO DESERTO", distance: 10200, difficulty: "BRUTAL", prize: 2300, index: 2, sky: ["#69678d", "#e2908b", "#ffcb95"], land: ["#bc8165", "#b3785d"], road: ["#5c5356", "#564e51"], accent: "#ffac6f" }
];
function getTrack(id) {
  return TRACKS.find((t) => t.id === id) ?? TRACKS[0];
}
function clamp(v, min, max) {
  return Math.min(max, Math.max(min, v));
}
var cornerCache = /* @__PURE__ */ new Map();
function trackCorners(trackId) {
  const track = getTrack(trackId), cached = cornerCache.get(track.id);
  if (cached) return cached;
  const corners = [];
  const strengths = [1.65, 2.3, 1.4, 2.05, 2.6, 1.75];
  let start = 650;
  for (let i = 0; start < track.distance - 500; i++) {
    const length = [300, 270, 330, 260][i % 4];
    corners.push({ start, end: start + length, bend: (i % 2 ? -1 : 1) * strengths[i % strengths.length] * (1 + track.index * 0.12), ramp: 85 });
    start += length + [270, 180, 320, 220][i % 4] - track.index * 35;
  }
  cornerCache.set(track.id, corners);
  return corners;
}
function curveAt(z, trackId) {
  const corner = trackCorners(trackId).find((c) => z >= c.start && z <= c.end);
  if (!corner) return 0;
  const t = clamp(Math.min(z - corner.start, corner.end - z) / corner.ramp, 0, 1);
  return corner.bend * t * t * (3 - 2 * t);
}
function cornerSpeed(curve, handling = 1.1) {
  return Math.sqrt(3e3 * handling / Math.max(0.01, Math.abs(curve)));
}
function cornerPace(z, trackId, handling = 1.1) {
  let speed = 120;
  for (let ahead = 0; ahead <= 240; ahead += 20) {
    const safe = cornerSpeed(curveAt(z + ahead, trackId), handling);
    speed = Math.min(speed, Math.sqrt(safe * safe + 2 * 19 * Math.max(0, ahead - 12)));
  }
  return speed;
}
function cornerForces(speed, handling, curve, shoulder = false) {
  const load = speed * speed * Math.abs(curve) / (3e3 * handling);
  const excess = Math.max(0, load - 1);
  return {
    lateral: (2.6 + speed * 0.0625) * handling * (shoulder ? 0.72 : 1) / (1 + excess * 0.9),
    drift: Math.sign(curve) * (4 * load + 4 * excess * excess),
    sliding: excess > 0.2
  };
}

// src/game/types.ts
var EMPTY_COMMAND = { throttle: 0, brake: 0, steer: 0, attack: null };

// src/game/simulation.ts
var STEP = 1 / 60;
var ROAD_HALF = 7;
var FALL_ARREST_RADIUS = 30;
var ATTACKS = {
  punch: { windup: 0.13, duration: 0.34, cooldown: 0.46, reach: 2.3, longitudinal: 4.8, damage: 16, push: 0.35 },
  kick: { windup: 0.25, duration: 0.52, cooldown: 0.8, reach: 2.6, longitudinal: 4.6, damage: 22, push: 1.1 },
  weapon: { windup: 0.21, duration: 0.48, cooldown: 0.72, reach: 3.6, longitudinal: 5.7, damage: 30, push: 0.55 }
};
function random(state) {
  let n = state.rng;
  n ^= n << 13;
  n ^= n >>> 17;
  n ^= n << 5;
  state.rng = n >>> 0;
  return state.rng / 4294967296;
}
function makeRider(id, name, profile, color, x, z) {
  return { id, name, profile, color, x, z, speed: 0, lean: 0, health: 100, integrity: 100, maxSpeed: 55, acceleration: 10, handling: 1, armor: 1, weapon: false, attack: null, cooldown: 0, crash: 0, immune: 0, targetX: x, decisionAt: 0, finishedAt: null, hits: 0, falls: 0 };
}
function createRace(trackId = "costa", save, seed = 88117) {
  const bike = BIKES.find((b) => b.id === save?.bikeId) ?? BIKES[0];
  const up = save?.upgrades[bike.id] ?? { engine: 0, armor: 0, handling: 0 };
  const player = makeRider("player", "VOC\xCA", "player", bike.color, 1.7, 0);
  Object.assign(player, { maxSpeed: bike.speed + up.engine * 2.5, acceleration: bike.acceleration + up.engine * 0.7, handling: bike.handling + up.handling * 0.1, armor: bike.armor + up.armor * 0.15, integrity: save?.condition[bike.id] ?? 100, weapon: true });
  const names = ["NINA", "COBRA", "DANTE", "LUNA", "ROCHA", "FA\xCDSCA", "ZECA"];
  const colors = ["#d87bfa", "#f28451", "#6cdace", "#ebbc5c", "#a4bde2", "#ef6f8a", "#e7e6dc"];
  const profiles = ["aggressive", "fast", "careful", "aggressive", "careful", "fast", "aggressive"];
  const riders = [player, ...names.map((name, i) => {
    const r = makeRider(`rival-${i}`, name, profiles[i], colors[i], i % 2 ? -1.5 : 3.8, 7 + i * 9);
    r.maxSpeed = (52 + i * 0.52 + getTrack(trackId).index * 2) * 1.12;
    r.acceleration = (9.8 + i % 3 * 0.6) * 1.2;
    r.weapon = i === 1 || i === 3 || i === 6;
    return r;
  })];
  const state = { version: 1, tick: 0, rng: seed || 1, trackId, mode: "countdown", countdown: 3.5, time: 0, riders, traffic: [], obstacles: [], events: [], collisions: {}, heat: 0, capture: 0, policeActive: false, result: null };
  const length = getTrack(trackId).distance;
  for (let z = 400, i = 0; z < length + 1800; z += 230 + random(state) * 160, i++) {
    const oncoming = i % 3 === 1;
    state.traffic.push({ id: `traffic-${i}`, x: (oncoming ? -1 : 1) * (i % 2 ? 1.75 : 5.25), z, speed: oncoming ? -18 - random(state) * 6 : 19 + random(state) * 9, color: ["#cdbc9b", "#a8b7c0", "#de785f", "#dcd7bb", "#679d9d"][i % 5], kind: i % 4 === 2 ? "van" : "car" });
  }
  for (let z = 1150, i = 0; z < length - 180; z += 630 - getTrack(trackId).index * 70, i++) {
    state.obstacles.push({ id: `obstacle-${i}`, x: i % 3 === 0 ? 4.8 : i % 3 === 1 ? -3.2 : 6.2, z, kind: i % 3 === 1 ? "barrier" : "oil" });
  }
  return state;
}
function ranking(state) {
  return state.riders.filter((r) => r.profile !== "police").slice().sort((a, b) => {
    if (a.finishedAt !== null && b.finishedAt !== null) return a.finishedAt - b.finishedAt;
    if (a.finishedAt !== null) return -1;
    if (b.finishedAt !== null) return 1;
    if (!!a.out !== !!b.out) return a.out ? 1 : -1;
    return b.z - a.z || a.id.localeCompare(b.id);
  });
}
function nearestTarget(state, rider, kind = "weapon") {
  const info = ATTACKS[kind];
  return state.riders.filter((r) => r.id !== rider.id && !r.out && !r.crash && !r.immune && r.finishedAt === null && Math.abs(r.z - rider.z) < info.longitudinal && Math.abs(r.x - rider.x) < info.reach).sort((a, b) => Math.abs(a.z - rider.z) + Math.abs(a.x - rider.x) - Math.abs(b.z - rider.z) - Math.abs(b.x - rider.x))[0];
}
function crashRider(state, rider) {
  if (rider.crash || rider.immune) return;
  rider.crash = 2.1 + rider.speed / 110;
  rider.speed *= 0.17;
  rider.integrity = Math.max(0, rider.integrity - 13 / rider.armor);
  rider.attack = null;
  rider.falls++;
  state.events.push({ type: "crash", actor: rider.id, text: "NO CH\xC3O! \u2212TEMPO \xB7 \u2212MOTO" });
}
function impact(state, rider, damage, push) {
  if (rider.immune || rider.crash) return;
  rider.health = Math.max(0, rider.health - damage);
  rider.x = clamp(rider.x + push, -10.5, 10.5);
  rider.speed *= 0.94;
  if (rider.health <= 0) crashRider(state, rider);
}
function botCommand(state, rider) {
  if (rider.out || rider.crash || rider.finishedAt !== null) return EMPTY_COMMAND;
  const police = rider.profile === "police";
  const player = police ? policeTarget(state, rider) : state.riders.filter((r) => r.id !== rider.id && r.profile !== "police" && !r.out && r.finishedAt === null).sort((a, b) => Math.abs(a.z - rider.z) - Math.abs(b.z - rider.z))[0];
  if (!player) return { ...EMPTY_COMMAND, brake: 1 };
  if (state.time >= rider.decisionAt) {
    rider.decisionAt = state.time + 0.55 + random(state) * 0.7;
    rider.targetX = police ? player.x : (random(state) > 0.23 ? 1 : -1) * (1.4 + random(state) * 3.6);
    if (rider.profile === "aggressive" && Math.abs(rider.z - player.z) < 24) rider.targetX = player.x + (rider.x < player.x ? -1.7 : 1.7);
  }
  let target = rider.targetX;
  let brake = 0;
  const dangers = [...state.traffic, ...state.obstacles].filter((t) => t.z - rider.z > -7 && t.z - rider.z < 30 + rider.speed * 1.5);
  if (dangers.some((t) => Math.min(Math.abs(t.x - rider.x), Math.abs(t.x - target)) < 2.8)) {
    const candidates = [-5.25, -1.75, 1.75, 5.25];
    const cost = (lane) => Math.abs(lane - rider.x) * 0.35 + dangers.reduce((sum, t) => sum + (Math.abs(t.x - lane) < 2.8 ? 30 - Math.max(0, t.z - rider.z) * 0.04 : 0), 0);
    target = candidates.sort((a, b) => cost(a) - cost(b))[0];
    rider.targetX = target;
    if (dangers.some((t) => t.z - rider.z < rider.speed * 0.4 && Math.abs(t.x - rider.x) < 2.5)) brake = 0.7;
  }
  for (const other of state.riders) {
    if (other.id === rider.id) continue;
    if (other.z - rider.z > 0 && other.z - rider.z < 14 && Math.abs(other.x - rider.x) < 1.05) {
      target = clamp(other.x + (rider.x < other.x ? -2 : 2), -5.5, 5.5);
    }
  }
  let attack = null;
  const nearby = nearestTarget(state, rider, rider.weapon ? "weapon" : "punch");
  if (nearby && rider.cooldown === 0 && (rider.profile !== "careful" || state.tick % 80 < 8)) attack = rider.weapon ? "weapon" : rider.profile === "aggressive" ? "kick" : "punch";
  const curve = curveAt(rider.z, state.trackId);
  const forces = cornerForces(rider.speed, rider.handling, curve, Math.abs(rider.x) > ROAD_HALF);
  const steering = clamp((target - rider.x) * 0.9 + forces.drift / forces.lateral, -1, 1);
  const pace = cornerPace(rider.z, state.trackId, rider.handling) * (rider.profile === "careful" ? 0.92 : rider.profile === "fast" ? 1.03 : 0.98);
  brake = Math.max(brake, clamp((rider.speed - pace) * 0.3, 0, 1));
  if (police && rider.z > player.z + 7) brake = Math.max(brake, 0.42);
  return { throttle: rider.speed > pace - 0.6 || brake > 0.1 ? 0 : 1, brake, steer: steering, attack };
}
function policeTarget(state, officer) {
  return state.riders.filter((r) => r.id !== officer.id && r.profile !== "police" && !r.out && r.finishedAt === null).sort((a, b) => Math.hypot(a.z - officer.z, a.x - officer.x) - Math.hypot(b.z - officer.z, b.x - officer.x) || a.id.localeCompare(b.id))[0];
}
function applyCommand(state, rider, command) {
  if (rider.out) {
    rider.speed = 0;
    rider.attack = null;
    return;
  }
  rider.cooldown = Math.max(0, rider.cooldown - STEP);
  rider.immune = Math.max(0, rider.immune - STEP);
  if (rider.finishedAt !== null) {
    rider.speed = Math.max(0, rider.speed - STEP * 12);
    return;
  }
  if (rider.crash > 0) {
    rider.crash = Math.max(0, rider.crash - STEP);
    rider.speed *= 0.975;
    rider.z += rider.speed * STEP;
    if (rider.crash === 0) {
      rider.health = 100;
      rider.immune = 2.4;
      rider.x = clamp(rider.x, -5.4, 5.4);
      rider.speed = 12;
    }
    return;
  }
  const onShoulder = Math.abs(rider.x) > ROAD_HALF;
  const curve = curveAt(rider.z, state.trackId);
  const shoulderLimit = Math.abs(curve) > 0.8 ? 0.38 : 0.56;
  const max = rider.maxSpeed * (onShoulder ? shoulderLimit : 1) * (0.92 + rider.integrity / 1250);
  const acceleration = command.throttle * rider.acceleration * (onShoulder ? 0.55 : 1) * (1 - 0.35 * rider.speed / rider.maxSpeed);
  rider.speed = clamp(rider.speed + (acceleration - command.brake * 29 - (command.throttle ? 1.2 : 3.6)) * STEP, 0, rider.maxSpeed);
  if (rider.speed > max) rider.speed = Math.max(max, rider.speed - STEP * (onShoulder ? 34 : 4));
  const steering = clamp(command.steer, -1, 1);
  const forces = cornerForces(rider.speed, rider.handling, curve, onShoulder);
  rider.x = clamp(rider.x + (steering * forces.lateral - forces.drift) * STEP, -10.5, 10.5);
  rider.lean += (steering * 0.32 - rider.lean) * 0.12;
  rider.z += rider.speed * STEP;
  rider.health = Math.min(100, rider.health + STEP * 1.15);
  if (Math.abs(rider.x) > 9.8 && rider.speed > 26 && !rider.immune) {
    rider.integrity -= STEP * 2.2;
  }
  if (command.attack && !rider.attack && rider.cooldown === 0 && (command.attack !== "weapon" || rider.weapon)) {
    const target = nearestTarget(state, rider, command.attack);
    rider.attack = { kind: command.attack, age: 0, side: target ? Math.sign(target.x - rider.x) || 1 : Math.sign(steering) || 1, hit: false };
    rider.cooldown = ATTACKS[command.attack].cooldown + (rider.profile === "player" ? 0 : 0.35);
    state.events.push({ type: "attack", actor: rider.id });
  }
}
function resolveAttacks(state) {
  for (const rider of state.riders) {
    const attack = rider.attack;
    if (!attack) continue;
    const spec = ATTACKS[attack.kind];
    const telegraph = rider.profile === "player" ? 0 : 0.25;
    attack.age += STEP;
    if (attack.age >= spec.windup + telegraph && !attack.hit) {
      attack.hit = true;
      const target = nearestTarget(state, rider, attack.kind);
      if (target && (Math.sign(target.x - rider.x) === attack.side || Math.abs(target.x - rider.x) < 0.4)) {
        impact(state, target, spec.damage, attack.side * spec.push);
        rider.hits++;
        const action = attack.kind === "kick" ? "CHUTE" : attack.kind === "weapon" ? "BASTONADA" : "SOCO";
        state.events.push({ type: "hit", actor: rider.id, target: target.id, text: target.id === "player" ? `VOC\xCA LEVOU ${action} \xB7 ${rider.name}` : `${target.name} \xB7 ${action}!` });
        if (rider.profile === "player") state.heat = clamp(state.heat + 12, 0, 100);
        if (attack.kind === "punch" && target.weapon) {
          target.weapon = false;
          rider.weapon = true;
          state.events.push({ type: "steal", actor: rider.id, text: "BAST\xC3O TOMADO!" });
        }
      }
    }
    if (attack.age >= spec.duration + telegraph) rider.attack = null;
  }
}
function mayCollide(state, a, b, cooldown = 1.4) {
  const key = [a, b].sort().join(":");
  if ((state.collisions[key] ?? -99) + cooldown > state.time) return false;
  state.collisions[key] = state.time;
  return true;
}
function resolveCollisions(state, oldZ) {
  for (const r of state.riders) {
    if (r.out || r.crash || r.immune || r.finishedAt !== null) continue;
    for (const t of state.traffic) {
      const relBefore = t.z - t.speed * STEP - (oldZ.get(r.id) ?? r.z);
      const relNow = t.z - r.z;
      if ((Math.abs(relNow) < 3.2 || relBefore * relNow < 0) && Math.abs(t.x - r.x) < 2.3 && mayCollide(state, r.id, t.id)) {
        r.integrity = Math.max(0, r.integrity - (t.speed < 0 ? 22 : 14) / r.armor);
        crashRider(state, r);
      }
    }
    for (const o of state.obstacles) {
      if (Math.abs(o.z - r.z) < 2 && Math.abs(o.x - r.x) < 1 && mayCollide(state, r.id, o.id, 3)) {
        if (o.kind === "oil") {
          impact(state, r, 23, r.x < 0 ? -0.8 : 0.8);
          r.speed *= 0.64;
          state.events.push({ type: "hit", actor: o.id, text: "\xD3LEO \xB7 SEM ADER\xCANCIA" });
        } else {
          r.integrity -= 15 / r.armor;
          crashRider(state, r);
        }
      }
    }
    for (const other of state.riders) {
      if (other.id <= r.id || other.out || other.crash || other.immune || other.finishedAt !== null) continue;
      if (Math.abs(other.z - r.z) < 2.1 && Math.abs(other.x - r.x) < 0.8 && mayCollide(state, r.id, other.id)) {
        const side = Math.sign(r.x - other.x) || 1;
        impact(state, r, 7, side * 0.35);
        impact(state, other, 7, -side * 0.35);
        state.events.push({ type: "hit", actor: r.id, text: "CONTATO!" });
      }
    }
  }
}
function createMultiplayerRace(trackId, players, seed = 88117, fillBots = false) {
  if (players.length < 2 || players.length > 8 || new Set(players.map((p) => p.id)).size !== players.length) throw new Error("A corrida precisa de 2 a 8 pilotos distintos.");
  const state = createRace(trackId, void 0, seed);
  const colors = ["#dcff74", "#d87bfa", "#6cdace", "#f28451", "#ebbc5c", "#a4bde2", "#ef6f8a", "#e7e6dc"];
  const base = state.riders[0];
  const bots = state.riders.slice(1);
  state.riders = players.map((p, i) => ({ ...base, id: p.id, name: p.name, color: colors[i], x: [-5.1, -1.7, 1.7, 5.1][i % 4], z: -(Math.floor(i / 4) * 8), profile: "player" }));
  if (fillBots) for (let i = players.length; i < 8; i++) {
    const bot = bots[i - players.length];
    state.riders.push({ ...base, id: `cpu-${i}`, name: `${bot.name} CPU`, profile: bot.profile, color: colors[i], x: [-5.1, -1.7, 1.7, 5.1][i % 4], targetX: [-5.1, -1.7, 1.7, 5.1][i % 4], z: -(Math.floor(i / 4) * 8) });
  }
  state.multiplayer = { humanIds: players.map((p) => p.id), results: {} };
  return state;
}
function finishRider(state, rider, reason, arrestCause) {
  if (state.multiplayer?.results[rider.id] || rider.out) return;
  if (reason !== "finish") {
    rider.out = reason;
    rider.attack = null;
  }
  const place = ranking(state).findIndex((r) => r.id === rider.id) + 1;
  const result = {
    reason,
    ...reason === "caught" ? { arrestCause: arrestCause ?? "stopped" } : {},
    place,
    time: rider.finishedAt ?? state.time,
    reward: state.multiplayer ? 0 : reason === "finish" ? Math.round(getTrack(state.trackId).prize * ([1, 0.8, 0.64, 0.5, 0.4, 0.32, 0.25, 0.2][place - 1] ?? 0.2)) : 120,
    hits: rider.hits,
    falls: rider.falls
  };
  if (state.multiplayer) {
    state.multiplayer.results[rider.id] = result;
    if (state.mode !== "finished" && state.multiplayer.humanIds.every((id) => state.multiplayer.results[id])) {
      state.mode = "finished";
      for (const bot of state.riders) if (bot.profile !== "player" && bot.profile !== "police" && !state.multiplayer.results[bot.id]) {
        finishRider(state, bot, bot.finishedAt !== null ? "finish" : "timeout");
      }
    }
  } else if (rider.id === "player") {
    state.result = result;
    state.mode = "finished";
  }
  state.events.push({ type: "finish", actor: rider.id });
}
function arrestFallenRiders(state) {
  for (const p of state.riders) {
    if (p.profile === "police" || p.out || p.finishedAt !== null || p.crash <= 0) continue;
    const near = state.riders.some((r) => r.profile === "police" && !r.out && r.crash <= 0 && r.integrity > 0 && Math.hypot(r.z - p.z, r.x - p.x) <= FALL_ARREST_RADIUS);
    if (near) {
      p.capture = 3;
      if (p.id === "player") state.capture = 3;
      finishRider(state, p, "caught", "fall");
    }
  }
  return state.mode === "finished";
}
function stepRace(state, commands = {}) {
  state.events = [];
  if (state.mode === "finished") return;
  state.tick++;
  if (state.mode === "countdown") {
    state.countdown -= STEP;
    if (state.countdown <= 0) {
      state.countdown = 0;
      state.mode = "racing";
    }
    return;
  }
  state.time += STEP;
  if (arrestFallenRiders(state)) return;
  const player = state.riders[0];
  const oldOrder = ranking(state).map((r) => r.id);
  const oldZ = new Map(state.riders.map((r) => [r.id, r.z]));
  for (const r of state.riders) applyCommand(state, r, commands[r.id] ?? (r.profile === "player" ? EMPTY_COMMAND : botCommand(state, r)));
  const active = state.riders.filter((r) => r.profile !== "police" && !r.out && r.finishedAt === null);
  const back = Math.min(...active.map((r) => r.z), player.z);
  for (const t of state.traffic) {
    t.z += t.speed * STEP;
    if (t.z < back - 100) t.z += getTrack(state.trackId).distance + 1800;
  }
  resolveAttacks(state);
  resolveCollisions(state, oldZ);
  if (arrestFallenRiders(state)) return;
  if (active.some((r) => r.profile === "player" && r.speed > 49)) state.heat = clamp(state.heat + STEP * 0.37, 0, 100);
  else state.heat = Math.max(0, state.heat - STEP * 0.15);
  const front = active.slice().sort((a, b) => b.z - a.z)[0];
  if (!state.policeActive && state.heat >= 48 && front && front.z > 1300) {
    const police = makeRider("police", "POL\xCDCIA", "police", "#e7e9e5", front.x + 1.5, front.z - 100);
    police.speed = 58;
    police.maxSpeed = 71 + getTrack(state.trackId).index * 2;
    police.acceleration = 12.5;
    police.weapon = true;
    state.riders.push(police);
    state.policeActive = true;
    state.events.push({ type: "police", actor: "police", text: "POL\xCDCIA NA ESTRADA \xB7 CUIDADO!" });
  }
  const officers = state.riders.filter((r) => r.profile === "police" && !r.crash && r.integrity > 0);
  const length = getTrack(state.trackId).distance;
  for (const r of state.riders) if (r.profile !== "police" && !r.out && r.finishedAt === null && r.z >= length) {
    r.finishedAt = state.time - (r.z - length) / Math.max(0.1, r.speed);
    r.z = length;
  }
  for (const r of state.riders) {
    if (r.profile === "police" || r.out) continue;
    const previous = !state.multiplayer && r.id === "player" ? state.capture : r.capture ?? 0;
    r.capture = officers.some((c) => Math.abs(c.z - r.z) < 18 && Math.abs(c.x - r.x) < 4 && r.speed < 8) ? previous + STEP : Math.max(0, previous - STEP * 2);
    if (r.id === "player") state.capture = r.capture;
    if (r.finishedAt !== null) {
      if (state.multiplayer ? !state.multiplayer.results[r.id] : r.id === "player") finishRider(state, r, "finish");
    } else if (r.integrity <= 0) finishRider(state, r, "wrecked");
    else if (r.capture >= 3) finishRider(state, r, "caught");
    else if (state.multiplayer && state.time >= 360) finishRider(state, r, "timeout");
  }
  for (const [index, r] of ranking(state).entries()) if (index < oldOrder.indexOf(r.id)) state.events.push({ type: "pass", actor: r.id });
  if (state.tick % 600 === 0) {
    for (const key of Object.keys(state.collisions)) if (state.time - state.collisions[key] > 5) delete state.collisions[key];
  }
}

// src/multiplayer/protocol.ts
var NET_VERSION = 3;
var MAX_PLAYERS = 8;
var ROOM_WAIT_MS = 6e4;
var READY_WAIT_MS = 5e3;
var RECONNECT_MS = 15e3;
function cleanName(value) {
  return typeof value === "string" ? value.normalize("NFKC").replace(/[^\p{L}\p{N} _.-]/gu, "").trim().slice(0, 18) || "Piloto" : "Piloto";
}
function cleanCommand(value) {
  if (!value || typeof value !== "object") return null;
  const c = value;
  if (![c.throttle, c.brake, c.steer].every((n) => typeof n === "number" && Number.isFinite(n))) return null;
  if (c.attack !== null && !["punch", "kick", "weapon"].includes(c.attack)) return null;
  return { throttle: Math.max(0, Math.min(1, c.throttle)), brake: Math.max(0, Math.min(1, c.brake)), steer: Math.max(-1, Math.min(1, c.steer)), attack: c.attack };
}
function cleanAttacks(value) {
  if (value === void 0) return [];
  if (!Array.isArray(value) || value.length > 8) return null;
  let previous = 0;
  const attacks = [];
  for (const a of value) {
    if (!a || !Number.isSafeInteger(a.seq) || a.seq <= previous || !["punch", "kick", "weapon"].includes(a.kind)) return null;
    attacks.push({ seq: a.seq, kind: a.kind });
    previous = a.seq;
  }
  return attacks;
}

// server/room.ts
var import_node_crypto = require("node:crypto");
var inputKey = (member) => `${member.id}:${member.epoch}`;
var secret = () => (0, import_node_crypto.randomBytes)(24).toString("base64url");
function makeMember(name, now) {
  return { id: `human-${(0, import_node_crypto.randomBytes)(8).toString("hex")}`, name: cleanName(name), ready: false, connected: true, token: secret(), epoch: secret(), lastSeen: now };
}
function makeRoom(code, trackId, member, now, fillBots = false) {
  if (!TRACKS.some((t) => t.id === trackId)) throw new Error("Estrada inv\xE1lida.");
  return {
    code,
    trackId,
    fillBots: fillBots === true,
    phase: "lobby",
    locked: false,
    deadline: now + ROOM_WAIT_MS,
    revision: 0,
    members: [member],
    race: null,
    ack: {},
    attackAck: {},
    updatedAt: now,
    createdAt: now,
    finishedAt: null
  };
}
function viewRoom(room, now) {
  return {
    code: room.code,
    trackId: room.trackId,
    fillBots: room.fillBots,
    phase: room.phase,
    locked: room.locked,
    deadline: room.deadline,
    revision: room.revision,
    serverNow: now,
    simulationAt: room.updatedAt,
    members: room.members.map(({ id, name, ready, connected }) => ({ id, name, ready, connected })),
    race: room.race,
    ack: room.ack,
    attackAck: room.attackAck
  };
}
function lobbyClock(room, now) {
  if (room.phase !== "lobby") return;
  const present = room.members.filter((p) => p.connected);
  if (present.length < 2) {
    if (room.locked) {
      room.locked = false;
      room.deadline = now + ROOM_WAIT_MS;
    }
    if (room.deadline !== null && now >= room.deadline) room.deadline = null;
    return;
  }
  if (room.deadline === null) room.deadline = now + ROOM_WAIT_MS;
  if (!room.locked && present.every((p) => p.ready)) room.deadline = Math.min(room.deadline, now + READY_WAIT_MS);
  if (room.deadline - now <= READY_WAIT_MS) room.locked = true;
  if (now < room.deadline) return;
  room.members = present;
  room.race = createMultiplayerRace(room.trackId, present, (0, import_node_crypto.randomBytes)(4).readUInt32LE(), room.fillBots);
  room.race.mode = "racing";
  room.race.countdown = 0;
  room.phase = "racing";
  room.updatedAt = now;
  room.deadline = null;
}
function joinRoom(room, member, now) {
  lobbyClock(room, now);
  if (room.phase !== "lobby" || room.locked) throw new Error("A largada j\xE1 foi fechada. Entre em outra sala.");
  room.members = room.members.filter((p) => p.connected);
  if (room.members.length >= MAX_PLAYERS) throw new Error("Sala cheia: o limite \xE9 de 8 pessoas.");
  room.members.push(member);
  lobbyClock(room, now);
}
function setReady(room, id, epoch, ready, now) {
  const member = room.members.find((p) => p.id === id && p.epoch === epoch);
  if (!member?.connected || room.phase !== "lobby" || room.locked) return;
  member.ready = ready;
  member.lastSeen = now;
  lobbyClock(room, now);
}
function depart(room, id, epoch, now, explicit = false) {
  const member = room.members.find((p) => p.id === id && p.epoch === epoch);
  if (!member) return;
  member.connected = false;
  member.ready = false;
  member.lastSeen = now;
  if (explicit && room.race) {
    const rider = room.race.riders.find((r) => r.id === id);
    if (rider && !room.race.multiplayer.results[id]) finishRider(room.race, rider, "left");
  }
  if (explicit && room.phase === "lobby") room.members = room.members.filter((p) => p !== member);
  lobbyClock(room, now);
}
function pulseRoom(room, inputs, now) {
  for (const m of room.members) {
    const input = inputs[inputKey(m)];
    if (input && input.at > m.lastSeen) {
      m.lastSeen = input.at;
      m.connected = true;
    }
    if (now - m.lastSeen > RECONNECT_MS) {
      m.connected = false;
      m.ready = false;
    }
  }
  if (room.phase === "lobby") {
    lobbyClock(room, now);
    return;
  }
  if (!room.race || room.phase === "finished") return;
  for (const m of room.members) {
    if (!m.connected && now - m.lastSeen > RECONNECT_MS) {
      const r = room.race.riders.find((r2) => r2.id === m.id);
      if (r) finishRider(room.race, r, "left");
    }
  }
  const steps = Math.min(120, Math.max(0, Math.floor((now - room.updatedAt) / (STEP * 1e3))));
  const commands = {};
  for (const m of room.members) {
    const latest = inputs[inputKey(m)];
    commands[m.id] = m.connected && latest && now - latest.at < 500 ? latest.command : { ...EMPTY_COMMAND, brake: 1 };
    if (latest && steps > 0) room.ack[m.id] = latest.seq;
  }
  const events = room.race.events.filter((e) => e.tick !== void 0 && e.tick > room.race.tick - 60);
  for (let i = 0; i < steps; i++) {
    const tickCommands = { ...commands };
    const started = [];
    for (const m of room.members) {
      const latest = inputs[inputKey(m)], rider = room.race.riders.find((r) => r.id === m.id);
      if (!latest || !m.connected || now - latest.at >= 500 || !rider) continue;
      const action = latest.attacks?.find((a) => a.seq > (room.attackAck[m.id] ?? 0));
      if (!action) continue;
      if (rider.out || rider.crash || rider.finishedAt !== null || action.kind === "weapon" && !rider.weapon) {
        room.attackAck[m.id] = action.seq;
        continue;
      }
      if (rider.attack || rider.cooldown > STEP) continue;
      tickCommands[m.id] = { ...commands[m.id], attack: action.kind };
      room.attackAck[m.id] = action.seq;
      started.push({ id: m.id, seq: action.seq });
    }
    stepRace(room.race, tickCommands);
    for (const a of started) {
      const rider = room.race.riders.find((r) => r.id === a.id);
      if (rider?.attack) rider.attack.id = a.seq;
    }
    events.push(...room.race.events.map((e) => ({ ...e, tick: room.race.tick })));
  }
  room.race.events = events.filter((e) => (e.tick ?? 0) > room.race.tick - 60).slice(-128);
  room.updatedAt += steps * STEP * 1e3;
  if (now - room.updatedAt > 2e3) room.updatedAt = now;
  if (room.race.mode === "finished") {
    room.phase = "finished";
    room.finishedAt = now;
  }
}

// server/store.ts
var import_ioredis = __toESM(require("ioredis"), 1);
var BusyRoom = class extends Error {
};
var clone = (value) => structuredClone(value);
var MemoryStore = class {
  shared = false;
  rooms = /* @__PURE__ */ new Map();
  inputs = /* @__PURE__ */ new Map();
  async create(room) {
    if (this.rooms.has(room.code)) return false;
    this.rooms.set(room.code, clone(room));
    return true;
  }
  async read(code) {
    return clone(this.rooms.get(code) ?? null);
  }
  async mutate(code, change, _retries, localInputs = {}) {
    const old = this.rooms.get(code);
    if (!old) throw new Error("Sala n\xE3o encontrada ou encerrada.");
    const all = this.inputs.get(code) ?? {};
    for (const [key, input] of Object.entries(localInputs)) if (!all[key] || all[key].seq < input.seq) all[key] = clone(input);
    this.inputs.set(code, all);
    const room = clone(old);
    change(room, clone(this.inputs.get(code) ?? {}));
    room.revision++;
    this.rooms.set(code, room);
    return clone(room);
  }
  async input(code, key, input) {
    const all = this.inputs.get(code) ?? {};
    if (!all[key] || all[key].seq < input.seq) all[key] = clone(input);
    this.inputs.set(code, all);
  }
  async close() {
    this.rooms.clear();
    this.inputs.clear();
  }
  sweep(now) {
    for (const [id, r] of this.rooms) if (now - r.createdAt > 30 * 6e4) {
      this.rooms.delete(id);
      this.inputs.delete(id);
    }
  }
};
var unquote = (s) => (s ?? "").trim().replace(/^['"]|['"]$/g, "");
var RedisStore = class {
  shared = true;
  command;
  redis;
  constructor(options) {
    if (options.url) {
      this.redis = new import_ioredis.default(options.url, { lazyConnect: true, maxRetriesPerRequest: 1, connectTimeout: 4e3, enableOfflineQueue: true });
      this.redis.on("error", () => {
      });
      this.command = (...args) => this.redis.call(args[0], ...args.slice(1));
    } else if (options.restUrl && options.token) {
      this.command = async (...args) => {
        const response = await fetch(options.restUrl, { method: "POST", headers: { Authorization: `Bearer ${options.token}`, "Content-Type": "application/json" }, body: JSON.stringify(args), signal: AbortSignal.timeout(4e3) });
        if (!response.ok) throw new Error("N\xE3o foi poss\xEDvel acessar as salas.");
        const data = await response.json();
        if (data.error) throw new Error("O armazenamento das salas n\xE3o respondeu.");
        return data.result;
      };
    } else throw new Error("Configure o Redis do multiplayer no servidor.");
  }
  key(code, field) {
    return `asfalto:online:v3:{${code}}:${field}`;
  }
  async create(room) {
    return await this.command("SET", this.key(room.code, "state"), JSON.stringify(room), "NX", "EX", 1800) === "OK";
  }
  async read(code) {
    const raw = await this.command("GET", this.key(code, "state"));
    return raw ? JSON.parse(raw) : null;
  }
  async input(code, key, input) {
    await this.command("EVAL", `local old=redis.call('HGET',KEYS[1],ARGV[1]); if not old or cjson.decode(old).seq<tonumber(ARGV[2]) then redis.call('HSET',KEYS[1],ARGV[1],ARGV[3]); redis.call('EXPIRE',KEYS[1],1800); return 1 end; return 0`, 1, this.key(code, "inputs"), key, input.seq, JSON.stringify(input));
  }
  async mutate(code, change, retries = 50, localInputs = {}) {
    const lock = this.key(code, "lock"), token = secret();
    let snapshot;
    for (let n = 0; n <= retries; n++) {
      const result = await this.command("EVAL", `
        if not redis.call('SET',KEYS[1],ARGV[1],'NX','PX',4000) then return {0} end
        local room=redis.call('GET',KEYS[2])
        if not room then redis.call('DEL',KEYS[1]); return {-1} end
        for key,raw in pairs(cjson.decode(ARGV[2])) do
          local input=cjson.decode(raw)
          local old=redis.call('HGET',KEYS[3],key)
          if not old or cjson.decode(old).seq<input.seq then redis.call('HSET',KEYS[3],key,raw) end
        end
        redis.call('EXPIRE',KEYS[3],1800)
        return {1,room,redis.call('HGETALL',KEYS[3])}
      `, 3, lock, this.key(code, "state"), this.key(code, "inputs"), token, JSON.stringify(Object.fromEntries(Object.entries(localInputs).map(([key, input]) => [key, JSON.stringify(input)]))));
      if (result[0] === -1) throw new Error("Sala n\xE3o encontrada ou encerrada.");
      if (result[0] === 1) {
        snapshot = result;
        break;
      }
      if (n < retries) await new Promise((resolve) => setTimeout(resolve, 20));
    }
    if (!snapshot) throw new BusyRoom("Sala ocupada por um instante. Tente novamente.");
    let committed = false;
    try {
      const room = JSON.parse(snapshot[1]), entries = snapshot[2], inputs = {};
      for (let i = 0; i < entries.length; i += 2) inputs[entries[i]] = JSON.parse(entries[i + 1]);
      change(room, inputs);
      room.revision++;
      const saved = await this.command("EVAL", `if redis.call('GET',KEYS[1])==ARGV[1] then redis.call('SET',KEYS[2],ARGV[2],'EX',1800); redis.call('DEL',KEYS[1]); return 1 end; return 0`, 2, lock, this.key(code, "state"), token, JSON.stringify(room));
      if (saved !== 1) throw new BusyRoom("A sala est\xE1 sincronizando. Tente novamente.");
      committed = true;
      return room;
    } finally {
      if (!committed) await this.command("EVAL", `if redis.call('GET',KEYS[1])==ARGV[1] then return redis.call('DEL',KEYS[1]) end; return 0`, 1, lock, token).catch(() => {
      });
    }
  }
  async close() {
    this.redis?.disconnect();
  }
};
function storeFromEnvironment() {
  const url = unquote(process.env.ASFALTO_REDIS_URL || process.env.REDIS_URL || process.env.KV_URL);
  const restUrl = unquote(process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL);
  const token = unquote(process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN);
  if (url || restUrl && token) return new RedisStore({ url, restUrl, token });
  if (process.env.VERCEL || process.env.NODE_ENV === "production") throw new Error("O multiplayer precisa do Redis configurado.");
  return new MemoryStore();
}

// server/service.ts
function createGameServer(store, options = {}) {
  const now = options.now ?? Date.now;
  const peers = /* @__PURE__ */ new Set();
  const revisions = /* @__PURE__ */ new Map();
  const pumping = /* @__PURE__ */ new Set();
  const latest = /* @__PURE__ */ new Map();
  const limits = /* @__PURE__ */ new Map();
  const server2 = (0, import_node_http.createServer)((req, res) => {
    res.setHeader("Cache-Control", "no-store");
    res.setHeader("Content-Type", "application/json");
    res.statusCode = 200;
    res.end(JSON.stringify({ service: "asfalto-bruto", version: NET_VERSION, multiplayer: true, sharedRooms: store.shared, region: process.env.VERCEL_REGION ?? "local" }));
  });
  const wss = new import_ws.WebSocketServer({ noServer: true, maxPayload: 4096, perMessageDeflate: false });
  server2.on("upgrade", (req, socket, head) => {
    const origin = req.headers.origin;
    const host = req.headers["x-forwarded-host"] || req.headers.host;
    const allowed = !origin || origin === `https://${host}` || origin === `http://${host}` || options.origins?.includes(origin);
    if (!allowed || peers.size >= 256) {
      socket.write("HTTP/1.1 403 Forbidden\r\n\r\n");
      socket.destroy();
      return;
    }
    const ip = req.socket.remoteAddress ?? "unknown";
    const limit = limits.get(ip) ?? { at: now(), count: 0 };
    if (now() - limit.at > 6e4) {
      limit.at = now();
      limit.count = 0;
    }
    limits.set(ip, limit);
    if (++limit.count > 80) {
      socket.write("HTTP/1.1 429 Too Many Requests\r\n\r\n");
      socket.destroy();
      return;
    }
    wss.handleUpgrade(req, socket, head, (ws) => wss.emit("connection", ws, req));
  });
  function send(peer, message) {
    if (peer.ws.readyState !== import_ws.WebSocket.OPEN) return;
    if (peer.ws.bufferedAmount > 512e3) {
      peer.ws.close(1013, "Conex\xE3o lenta");
      return;
    }
    peer.ws.send(JSON.stringify(message));
  }
  function broadcast(room) {
    latest.set(room.code, room);
    if ((revisions.get(room.code) ?? -1) >= room.revision) return;
    revisions.set(room.code, room.revision);
    const message = { type: "state", room: viewRoom(room, now()) };
    for (const peer of peers) if (peer.code === room.code) send(peer, message);
  }
  async function flush(peer) {
    if (peer.writing || !peer.code) return;
    peer.writing = true;
    try {
      while (peer.pending && peer.code) {
        const pending = peer.pending;
        peer.pending = void 0;
        await store.input(peer.code, `${peer.id}:${peer.epoch}`, pending);
      }
    } catch {
      send(peer, { type: "error", message: "A conex\xE3o com a sala est\xE1 inst\xE1vel. Reconectando\u2026" });
      peer.ws.close(1013);
    } finally {
      peer.writing = false;
    }
  }
  async function attach(peer, room, member) {
    if (peer.ws.readyState !== import_ws.WebSocket.OPEN) {
      await store.mutate(room.code, (r) => depart(r, member.id, member.epoch, now())).catch(() => {
      });
      return;
    }
    peer.code = room.code;
    peer.id = member.id;
    peer.epoch = member.epoch;
    peer.seq = room.ack[member.id] ?? 0;
    send(peer, { type: "welcome", id: member.id, token: member.token, room: viewRoom(room, now()) });
    broadcast(room);
  }
  wss.on("connection", (ws) => {
    const peer = { ws, code: "", id: "", epoch: "", seq: 0, writing: false, lastSeen: now(), alive: true };
    peers.add(peer);
    let busy = false, messages = 0, windowStart = now();
    ws.on("pong", () => {
      peer.alive = true;
      peer.lastSeen = now();
    });
    ws.on("message", async (raw) => {
      if (now() - windowStart > 1e3) {
        messages = 0;
        windowStart = now();
      }
      if (++messages > 100) {
        ws.close(1008, "Muitas mensagens");
        return;
      }
      let data;
      try {
        data = JSON.parse(raw.toString());
      } catch {
        send(peer, { type: "error", message: "Mensagem inv\xE1lida." });
        return;
      }
      if (!data || typeof data !== "object") return;
      peer.lastSeen = now();
      if (data.type === "ping") {
        send(peer, { type: "pong", sentAt: Number(data.sentAt) || 0, serverNow: now() });
        return;
      }
      if (data.type === "input") {
        const command = cleanCommand(data.command), attacks = cleanAttacks(data.attacks);
        if (!peer.code || !command || !attacks || !Number.isSafeInteger(data.seq) || data.seq <= peer.seq) return;
        peer.seq = data.seq;
        peer.pending = peer.latestInput = { seq: data.seq, command, attacks, at: now() };
        void flush(peer);
        return;
      }
      if (busy) return;
      busy = true;
      try {
        if (["create", "join", "resume"].includes(data.type)) {
          if (peer.code) throw new Error("Voc\xEA j\xE1 est\xE1 em uma sala.");
          if (data.version !== NET_VERSION) throw new Error("Atualize a p\xE1gina para entrar nesta vers\xE3o.");
          if (data.type === "create") {
            const member = makeMember(data.name, now());
            let room;
            do {
              room = makeRoom((0, import_node_crypto2.randomBytes)(4).toString("hex").slice(0, 6).toUpperCase(), data.trackId, member, now(), data.fillBots === true);
            } while (!await store.create(room));
            await attach(peer, room, member);
          } else {
            const code = String(data.code ?? "").toUpperCase();
            if (!/^[A-F0-9]{6}$/.test(code)) throw new Error("Digite o c\xF3digo de 6 caracteres da sala.");
            let member = makeMember(data.name, now());
            const room = await store.mutate(code, (r) => {
              if (data.type === "join") joinRoom(r, member, now());
              else {
                const found = r.members.find((m) => typeof data.token === "string" && m.token === data.token);
                if (!found || now() - found.lastSeen > RECONNECT_MS && r.phase === "lobby") throw new Error("Sua vaga expirou. Entre novamente.");
                if (r.race && now() - found.lastSeen > RECONNECT_MS) {
                  const rider = r.race.riders.find((p) => p.id === found.id);
                  if (rider) finishRider(r.race, rider, "left");
                }
                found.connected = true;
                found.lastSeen = now();
                found.epoch = secret();
                member = found;
                lobbyClock(r, now());
              }
            });
            await attach(peer, room, member);
          }
        } else if (data.type === "ready" && peer.code && typeof data.ready === "boolean") {
          broadcast(await store.mutate(peer.code, (r) => setReady(r, peer.id, peer.epoch, data.ready, now())));
        } else if (data.type === "leave" && peer.code) {
          const code = peer.code;
          peer.code = "";
          peer.pending = void 0;
          broadcast(await store.mutate(code, (r) => depart(r, peer.id, peer.epoch, now(), true)));
          send(peer, { type: "left" });
        }
      } catch (error) {
        const message = error instanceof Error && !(error instanceof TypeError) ? error.message : "N\xE3o foi poss\xEDvel entrar na sala.";
        const fatal = data.type === "resume" && /vaga expirou|não encontrada|Atualize/.test(message);
        send(peer, { type: "error", message, fatal });
        if (data.type === "resume" && !fatal) peer.ws.close(1013);
      } finally {
        busy = false;
      }
    });
    ws.on("close", () => {
      peers.delete(peer);
      peer.pending = void 0;
      if (peer.code) void store.mutate(peer.code, (r) => depart(r, peer.id, peer.epoch, now())).then(broadcast).catch(() => {
      });
    });
    ws.on("error", () => {
    });
  });
  async function pump(code) {
    if (pumping.has(code)) return;
    pumping.add(code);
    try {
      const inputs = {};
      for (const p of peers) if (p.code === code && p.latestInput) inputs[`${p.id}:${p.epoch}`] = p.latestInput;
      broadcast(await store.mutate(code, (r, inputs2) => pulseRoom(r, inputs2, now()), 0, inputs));
    } catch (e) {
      if (e instanceof BusyRoom) {
        const room = await store.read(code).catch(() => null);
        if (room) broadcast(room);
      } else for (const peer of peers) if (peer.code === code) {
        send(peer, { type: "error", message: "N\xE3o foi poss\xEDvel sincronizar a sala. Reconectando\u2026" });
        peer.ws.close(1013);
      }
    } finally {
      pumping.delete(code);
    }
  }
  let cycles = 0;
  const timer = setInterval(() => {
    cycles++;
    for (const peer of peers) void flush(peer);
    const codes = new Set([...peers].map((p) => p.code).filter(Boolean));
    for (const code of codes) if (latest.get(code)?.phase === "racing" || latest.get(code)?.locked || cycles % 10 === 0) void pump(code);
    if (cycles % 100 === 0) {
      for (const peer of peers) {
        if (!peer.alive || !peer.code && now() - peer.lastSeen > 2e4) {
          peer.ws.terminate();
          continue;
        }
        peer.alive = false;
        peer.ws.ping();
        if (peer.code && latest.get(peer.code)?.phase === "lobby") void store.mutate(peer.code, (r) => {
          const m = r.members.find((m2) => m2.id === peer.id && m2.epoch === peer.epoch);
          if (m) {
            m.lastSeen = now();
            m.connected = true;
          }
        }).then(broadcast).catch(() => {
        });
      }
      for (const code of latest.keys()) if (!codes.has(code)) {
        latest.delete(code);
        revisions.delete(code);
      }
      for (const [ip, l] of limits) if (now() - l.at > 6e4) limits.delete(ip);
      if (store instanceof MemoryStore) store.sweep(now());
    }
  }, 50);
  timer.unref();
  return { server: server2, wss, async close() {
    clearInterval(timer);
    for (const p of peers) p.ws.terminate();
    await new Promise((resolve) => wss.close(() => resolve()));
    await new Promise((resolve) => server2.close(() => resolve()));
    await store.close();
  } };
}

// api/asfalto.ts
var server;
try {
  server = createGameServer(storeFromEnvironment()).server;
} catch {
  server = (0, import_node_http2.createServer)((_req, res) => {
    res.writeHead(503, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "Multiplayer indispon\xEDvel: configure o Redis no Vercel. O modo individual continua dispon\xEDvel." }));
  });
}
var asfalto_default = server;
module.exports = module.exports.default;
