// Generated by sources/asfalto-bruto/scripts/export-jogos.mjs. Do not edit this bundle directly.
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api/asfalto.ts
var asfalto_exports = {};
__export(asfalto_exports, {
  default: () => asfalto_default
});
module.exports = __toCommonJS(asfalto_exports);
var import_node_http2 = require("node:http");

// src/version.ts
var GAME_VERSION = "1.2.1-beta";

// server/service.ts
var import_node_http = require("node:http");
var import_node_crypto2 = require("node:crypto");
var import_node_net = require("node:net");
var import_ws = require("ws");

// src/game/conditions.ts
var CONDITIONS = [
  { id: "day", name: "Dia", icon: "\u2600", description: "C\xE9u aberto e boa visibilidade." },
  { id: "sunset", name: "Entardecer", icon: "\u25D2", description: "Luz dourada e a estrada de sempre." },
  { id: "night", name: "Noite", icon: "\u263E", description: "Luar, far\xF3is e refletores pelo caminho." },
  { id: "rain", name: "Chuva", icon: "\u2602", description: "Piso molhado. Freie antes e fa\xE7a curvas suaves." }
];
function raceCondition(value) {
  return CONDITIONS.some((c) => c.id === value) ? value : "sunset";
}
var roadGrip = (value) => raceCondition(value) === "rain" ? 0.82 : 1;
var brakeGrip = (value) => raceCondition(value) === "rain" ? 0.88 : 1;
function decorHash(seed) {
  let n = seed | 0;
  n = Math.imul(n ^ n >>> 16, 73244475);
  n = Math.imul(n ^ n >>> 16, 73244475);
  return ((n ^ n >>> 16) >>> 0) / 4294967296;
}
function coastalEvent(trackId, seed) {
  if (trackId !== "costa" || decorHash(seed ^ 119317776) >= 0.33) return void 0;
  const sites = [440, 1540, 2910, 4180, 6170];
  return { kind: "mermaid", z: sites[Math.floor(decorHash(seed ^ 24951378) * sites.length)], startedAt: null, duration: 8 };
}
function advanceScenicEvent(state) {
  const event = state.scenicEvent;
  if (!event || event.startedAt !== null || state.mode !== "racing") return;
  const humans = state.riders.filter((r) => r.profile === "player" && !r.out && r.finishedAt === null);
  if (event.kind === "truckPassenger") {
    const truck = state.traffic.find((t) => t.id === event.trafficId);
    if (truck && humans.some((r) => truck.z >= r.z - 8 && truck.z - r.z <= 180)) event.startedAt = state.time;
  } else if (humans.some((r) => r.z >= event.z - 180)) event.startedAt = state.time;
}

// src/game/rural.ts
var RURAL_CORNERS = [
  [650, 990, 1.8],
  [1170, 1450, -2.15],
  [1610, 1900, 2.35],
  [2200, 2510, -1.85],
  [2680, 2970, 2.5],
  [3160, 3460, -2.2],
  [3700, 4e3, 2.1],
  [4180, 4500, -2.45],
  [4700, 5e3, 1.95],
  [5230, 5530, -2.35],
  [5680, 5980, 2.15],
  [6200, 6560, -1.85]
].map(([start, end, bend]) => ({ start, end, bend, ramp: 100 }));
var RURAL_BANKS = [
  { start: 480, end: 1100, side: -1 },
  { start: 1500, end: 2030, side: 1 },
  { start: 2620, end: 3060, side: -1 },
  { start: 3610, end: 4120, side: 1 },
  { start: 4650, end: 5130, side: -1 },
  { start: 5620, end: 6100, side: 1 }
];
function bankStrength(z, side) {
  const bank = RURAL_BANKS.find((b) => b.side === side && z > b.start && z < b.end);
  if (!bank) return 0;
  const t = Math.min(1, (z - bank.start) / 64, (bank.end - z) / 64);
  return t * t * (3 - 2 * t);
}
function ruralSlope(z) {
  return Math.cos(z / 310) * 19 / 310 + Math.cos(z / 137) * 4 / 137;
}
function ruralTraffic(random2) {
  const vehicles = [];
  for (let z = 720, i = 0; z < 9e3; z += 690 + random2() * 150, i++) {
    const tractor = i % 3 !== 2, oncoming = i % 4 === 2 || i % 5 === 3;
    vehicles.push({
      id: `farm-${i}`,
      kind: tractor ? "tractor" : "car",
      x: oncoming ? -2.1 : 2.1,
      z,
      speed: (oncoming ? -1 : 1) * (tractor ? 7 + random2() * 3 : 17 + random2() * 4),
      color: tractor ? i % 2 ? "#d78143" : "#6e9654" : ["#d5c29f", "#85a6ad", "#d28a63"][i % 3]
    });
  }
  return vehicles;
}
function ruralObstacles(condition) {
  return [2010, 3520, 5070, 6650].map((z, i) => ({ id: `soil-${i}`, kind: condition === "rain" ? "mud" : "gravel", x: i % 2 ? -2.7 : 2.7, z }));
}
function ruralEvent(seed, condition) {
  if (decorHash(seed ^ 5947824) >= 0.33) return void 0;
  const sites = [2070, 3530, 5150, 6710];
  return { kind: raceCondition(condition) === "night" ? "boitata" : "saci", z: sites[Math.floor(decorHash(seed ^ 461729) * sites.length)], startedAt: null, duration: 8 };
}

// src/game/road-profile.ts
var roadHalf = (trackId) => trackId === "terra" ? 4.2 : 7;
var lateralLimit = (trackId) => roadHalf(trackId) + 3.5;
var roadLanes = (trackId) => trackId === "terra" ? [-2.1, 2.1] : [-5.25, -1.75, 1.75, 5.25];
var surfaceGrip = (trackId, condition) => roadGrip(condition) * (trackId === "terra" ? 0.92 : 1);
var surfaceBraking = (trackId, condition) => brakeGrip(condition) * (trackId === "terra" ? 0.94 : 1);
var surfaceDrag = (trackId, condition) => trackId === "terra" ? raceCondition(condition) === "rain" ? 1.1 : 0.6 : 0;
function trafficShape(trackId, kind) {
  const width = kind === "tractor" ? 3 : kind === "truck" ? 4.5 : trackId === "terra" ? 3.1 : 3.7;
  return { width, height: width * (kind === "tractor" ? 1.08 : kind === "truck" ? 1.25 : 0.94), contact: kind === "tractor" ? 1.95 : kind === "truck" ? 2.7 : trackId === "terra" ? 2 : 2.3, length: kind === "tractor" ? 4.2 : kind === "truck" ? 5.5 : 3.2 };
}
function trafficAvoidance(trackId, kind, braking = false) {
  if (trackId !== "terra") return kind === "truck" ? braking ? 3.1 : 3.2 : braking ? 2.5 : 2.8;
  return trafficShape(trackId, kind === "tractor" ? "tractor" : "car").contact + (braking ? 0.2 : 0.5);
}

// src/game/hazards.ts
var TREE_SITES = [{ z: 2040, x: -1.75 }, { z: 4530, x: 1.75 }, { z: 7150, x: -1.75 }];
var RAMP_SITES = [{ z: 2060, x: 2.1 }, { z: 3560, x: -2.1 }, { z: 5130, x: 2.1 }, { z: 6730, x: -2.1 }];
var isRamp = (o) => o.kind === "dirtRamp" || o.kind === "woodRamp";
var trafficDirection = (t) => t.heading ?? (t.speed < 0 ? -1 : 1);
function trackHazards(track, seed) {
  if (track === "serra") return TREE_SITES.map((site, i) => ({ id: `fallen-tree-${i}`, kind: "fallenTree", width: 10.5, ...site }));
  if (track === "terra") return RAMP_SITES.map((site, i) => ({ id: `ramp-${i}`, kind: i % 2 ? "woodRamp" : "dirtRamp", ...site }));
  if (track !== "deserto") return [];
  return [1450, 2350, 3650, 4750, 5950, 7150, 8250].map((z, i) => {
    const animal = i % 3 === 1, from = i % 2 ? 14 : -14, speed = animal ? 2.6 : 5.4, period = animal ? 23 : 13;
    return {
      id: `desert-crossing-${i}`,
      kind: animal ? "armadillo" : "tumbleweed",
      x: from,
      z,
      motion: { from, to: -from, speed, phase: decorHash(seed ^ 20954 + i * 719) * period, period }
    };
  });
}
function obstacleX(o, time) {
  const m = o.motion;
  if (!m) return o.x;
  const age = ((time + m.phase) % m.period + m.period) % m.period;
  return m.from + Math.sign(m.to - m.from) * Math.min(Math.abs(m.to - m.from), age * m.speed);
}
function obstacleShape(o) {
  const width = o.width ?? (o.kind === "fallenTree" ? 10.5 : isRamp(o) ? 2.3 : o.kind === "armadillo" ? 1.6 : o.kind === "tumbleweed" ? 1.8 : o.kind === "cone" ? 1.1 : 2);
  return {
    width,
    contact: o.kind === "fallenTree" ? width / 2 + 0.5 : o.width ? width / 2 + 0.3 : o.kind === "cone" ? 0.55 : o.kind === "armadillo" ? 0.95 : isRamp(o) ? 1.1 : 1,
    length: o.kind === "fallenTree" ? 1.7 : isRamp(o) ? 1.8 : o.kind === "armadillo" ? 0.85 : o.kind === "tumbleweed" ? 0.9 : 2
  };
}
function dangerClearance(track, danger, braking = false) {
  if (!("speed" in danger) && isRamp(danger)) return 0;
  return Math.max(trafficAvoidance(track, danger.kind, braking), "speed" in danger ? 0 : obstacleShape(danger).contact + 0.2);
}

// src/game/port.ts
var PORT_CORNERS = [
  { start: 800, end: 1550, bend: 1.15, ramp: 110 },
  { start: 1740, end: 2020, bend: -0.9, ramp: 90 },
  { start: 2450, end: 2710, bend: 1.95, ramp: 85 },
  { start: 2800, end: 3070, bend: -2.1, ramp: 85 },
  { start: 3440, end: 3710, bend: 1.6, ramp: 90 },
  { start: 3920, end: 4180, bend: -2.15, ramp: 85 },
  { start: 4360, end: 4680, bend: 1.5, ramp: 90 },
  { start: 5120, end: 5580, bend: -0.9, ramp: 110 },
  { start: 5860, end: 6210, bend: 1.1, ramp: 100 },
  { start: 6550, end: 6870, bend: -1.75, ramp: 90 },
  { start: 7080, end: 7420, bend: 2.15, ramp: 90 }
];
var PORT_WORKS = [
  { start: 2260, end: 2400, side: 1, queue: true },
  { start: 2910, end: 3050, side: -1, queue: true },
  { start: 6370, end: 6490, side: 1, queue: false }
];
function portObstacles() {
  return PORT_WORKS.flatMap((work, i) => [
    ...[0, 30, 60, 100, 140].map((offset, n) => ({ id: `port-cone-${i}-${n}`, kind: "cone", x: work.side * (work.queue ? 0.5 : n === 0 ? 6.3 : n === 1 ? 5.7 : 4.5), z: work.start + offset })),
    ...[65, 110].map((offset, n) => ({ id: `port-block-${i}-${n}`, kind: "concrete", x: work.side * (work.queue ? 3.5 : 5.8), z: work.start + offset, ...work.queue ? { width: 6.8 } : {} }))
  ]);
}
function portTraffic(random2) {
  const traffic = [];
  for (let z = 900, i = 0; z < 9600; z += 560 + random2() * 110, i++) {
    const oncoming = i % 4 === 1, truck = oncoming || i % 4 === 2;
    const vehicle = {
      id: `port-traffic-${i}`,
      kind: truck ? "truck" : i % 3 === 0 ? "van" : "car",
      x: oncoming ? -1.75 : 1.75,
      z,
      speed: oncoming ? -13 - random2() * 4 : truck ? 14 + random2() * 4 : 19 + random2() * 6,
      color: ["#bf704f", "#8babb2", "#d4ba80", "#548e88"][i % 4]
    };
    if (!PORT_WORKS.some((w) => w.queue && Math.sign(vehicle.x) === w.side && z > w.start - 140 && z < w.end + 140)) traffic.push(vehicle);
  }
  for (const [i, w] of PORT_WORKS.entries()) if (w.queue) for (let n = 0; n < 5; n++) traffic.push({
    id: `port-queue-${i}-${n}`,
    kind: "car",
    x: w.side * 1.75,
    z: w.side > 0 ? w.start - 18 - n * 12 : w.end + 18 + n * 12,
    speed: 0,
    heading: w.side,
    queued: true,
    color: ["#d9d1ab", "#769ea2", "#c77454", "#dedfce", "#698673"][n]
  });
  return traffic;
}
function stopAtPortQueue(traffic, dt) {
  for (const direction of [1, -1]) {
    const vehicles = traffic.filter((t) => trafficDirection(t) === direction).sort((a, b) => direction * (b.z - a.z));
    for (const t of vehicles) {
      if (!t.speed) continue;
      const ahead = vehicles.filter((v) => v.id !== t.id && v.queued && Math.abs(v.x - t.x) < 2 && (v.z - t.z) * direction >= 0).sort((a, b) => direction * (a.z - b.z))[0];
      const gap = t.kind === "truck" ? 14 : 12;
      if (ahead && (ahead.z - t.z) * direction < gap + Math.abs(t.speed) * dt) {
        t.z = ahead.z - direction * gap;
        t.heading = direction;
        t.speed = 0;
        t.queued = true;
      }
    }
  }
}
function portPassengerEvent(seed, traffic) {
  if (decorHash(seed ^ 7402257) >= 0.33) return void 0;
  const trucks = traffic.filter((t) => t.kind === "truck" && t.speed < 0);
  if (!trucks.length) return void 0;
  const truck = trucks[Math.floor(decorHash(seed ^ 3250839) * trucks.length)];
  return { kind: "truckPassenger", trafficId: truck.id, z: truck.z, startedAt: null, duration: 8 };
}

// src/game/bikes.ts
var BIKES = [
  { id: "ferro", nitroCapacity: 2, name: "Ferro 500", class: "STREET", style: "street", price: 0, speed: 64, acceleration: 13.2, handling: 1.1, armor: 1, color: "#dfff71", tagline: "Equilibrada para aprender a rua. Leve no bolso, firme na pista." },
  { id: "veneno", nitroCapacity: 3, name: "Veneno 750", class: "ESPORTIVA", style: "sport", price: 3e4, speed: 73, acceleration: 15, handling: 1.2, armor: 0.95, color: "#ee734d", tagline: "Carenagem afiada e motor forte. Acelera muito, exige cuidado no contato." },
  { id: "brutal", nitroCapacity: 5, name: "Brutal 1000", class: "MUSCLE", style: "muscle", price: 1e5, speed: 78, acceleration: 12.5, handling: 0.95, armor: 1.4, color: "#b6a1fb", tagline: "Pneu largo e a maior final. Freie cedo para domar o peso nas curvas." },
  { id: "falcao", nitroCapacity: 2, name: "Falc\xE3o 450", class: "SUPERMOTO", style: "supermoto", price: 1e4, speed: 60, acceleration: 15.6, handling: 1.6, armor: 0.82, color: "#74dfe9", tagline: "Alta, estreita e muito \xE1gil. Contorna r\xE1pido, perde nas retas e no impacto." },
  { id: "estradeira", nitroCapacity: 2, name: "Estradeira 900", class: "CRUISER", style: "cruiser", price: 18e3, speed: 66, acceleration: 12.4, handling: 1, armor: 1.55, color: "#e6b965", tagline: "Custom de banco baixo, cromados e alforjes. Aguenta a briga, pede uma curva mais aberta." },
  { id: "lobo", nitroCapacity: 3, name: "Lobo 1200", class: "CHOPPER", style: "chopper", price: 45e3, speed: 71, acceleration: 11.4, handling: 0.82, armor: 1.7, color: "#c57566", tagline: "Garfo longo, guid\xE3o alto e muito metal. A mais resistente; prepare bem a frenagem." },
  { id: "agulha", nitroCapacity: 3, name: "Agulha 600", class: "CAF\xC9 RACER", style: "cafe", price: 65e3, speed: 69, acceleration: 14.5, handling: 1.42, armor: 0.9, color: "#91b897", tagline: "Tanque cl\xE1ssico, banco de couro e dire\xE7\xE3o precisa. Boa sa\xEDda de curva, pouca prote\xE7\xE3o." }
];
function getBike(id) {
  return BIKES.find((b) => b.id === id) ?? BIKES[0];
}
var supportsKneeDown = (bikeId) => getBike(bikeId).style !== "chopper";

// src/game/equipment.ts
var NITRO_DURATION = 5;
var NITRO_MULTIPLIER = 1.1;
var KNEE_DURATION = 4;
var WET_KNEE_LIMIT = 2;
function nitroCount(bikeId, value) {
  return typeof value === "number" && Number.isInteger(value) ? Math.max(0, Math.min(getBike(bikeId).nitroCapacity, value)) : 0;
}
var KNEE_PADS = [
  { id: "white", name: "Branca", color: "#e7eddf", price: 450, grip: 0.12 },
  { id: "green", name: "Verde", color: "#a8ef66", price: 900, grip: 0.22 },
  { id: "blue", name: "Azul", color: "#67c5ff", price: 1600, grip: 0.32 },
  { id: "purple", name: "Roxa", color: "#c59aff", price: 2600, grip: 0.42 },
  { id: "gold", name: "Dourada", color: "#ffd16a", price: 4e3, grip: 0.55 }
];
function getKneePad(id) {
  return KNEE_PADS.find((p) => p.id === id);
}
function equippedKneePad(save) {
  return save?.ownedKneePads?.includes(save.kneePadId ?? "") ? getKneePad(save.kneePadId) : void 0;
}
var ramp = (value) => Math.max(0, Math.min(1, value));
function kneeSupport(rider, curve, trackId = "costa") {
  if ((rider.wheelieTime ?? 0) > 0 || (rider.jumpTime ?? 0) > 0 || !getKneePad(rider.kneePadId) || !supportsKneeDown(rider.bikeId) || !(rider.kneeTime > 0) || rider.kneeSide !== Math.sign(curve) || rider.crash || rider.out || rider.finishedAt !== null || Math.abs(rider.x) > roadHalf(trackId)) return 0;
  return ramp((rider.speed - 20) / 10) * ramp((Math.abs(curve) - 0.15) / 0.5);
}
function kneeContact(rider, curve, trackId = "costa") {
  return kneeSupport(rider, curve, trackId) > 0.35 && rider.attack?.kind !== "kick";
}
function cornerHandling(rider, curve, trackId = "costa") {
  return rider.handling * (1 + (getKneePad(rider.kneePadId)?.grip ?? 0) * kneeSupport(rider, curve, trackId));
}
function plannedCornerHandling(handling, kneePadId) {
  return handling * (1 + (getKneePad(kneePadId)?.grip ?? 0));
}

// src/game/content.ts
var TRACKS = [
  { id: "costa", name: "Costa do Sol", region: "RODOVIA LITOR\xC2NEA", distance: 8400, difficulty: "NORMAL", prize: 1400, index: 0, level: 0, theme: "coast", sky: ["#567d9b", "#e0a6aa", "#fbd4ad"], land: ["#779b77", "#699271"], road: ["#555a5b", "#505557"], accent: "#deff70" },
  { id: "serra", name: "Serra da Fuma\xE7a", region: "ESTRADA DA MONTANHA", distance: 9200, difficulty: "DIF\xCDCIL", prize: 1850, index: 1, level: 1, theme: "mountain", sky: ["#555f83", "#b794b1", "#f2c2b5"], land: ["#728b70", "#637e67"], road: ["#555962", "#50545c"], accent: "#b9a0f8" },
  { id: "deserto", name: "Vale Vermelho", region: "FRONTEIRA DO DESERTO", distance: 10200, difficulty: "BRUTAL", prize: 2300, index: 2, level: 2, theme: "desert", sky: ["#69678d", "#e2908b", "#ffcb95"], land: ["#bc8165", "#b3785d"], road: ["#5c5356", "#564e51"], accent: "#ffac6f" },
  { id: "porto", name: "Porto Ferrugem", region: "DISTRITO PORTU\xC1RIO", distance: 7800, difficulty: "T\xC9CNICA", prize: 2200, index: 3, level: 1, theme: "port", sky: ["#52697b", "#c58c79", "#f2cc98"], land: ["#797d76", "#70766f"], road: ["#535f62", "#4b575b"], accent: "#ffc16a" },
  { id: "terra", name: "Terra Brava", region: "CAMINHOS DO INTERIOR", distance: 7200, difficulty: "TERRA", prize: 2500, index: 4, level: 1, theme: "rural", sky: ["#577f91", "#dfa385", "#f7d5a4"], land: ["#829454", "#78874c"], road: ["#b77749", "#b27346"], accent: "#efbd80" }
];
function getTrack(id) {
  return TRACKS.find((t) => t.id === id) ?? TRACKS[0];
}
function clamp(v, min, max) {
  return Math.min(max, Math.max(min, v));
}
var cornerCache = /* @__PURE__ */ new Map();
function trackCorners(trackId) {
  const track = getTrack(trackId), cached = cornerCache.get(track.id);
  if (cached) return cached;
  if (track.theme === "port") return PORT_CORNERS;
  if (track.theme === "rural") return RURAL_CORNERS;
  const corners = [];
  const strengths = [1.65, 2.3, 1.4, 2.05, 2.6, 1.75];
  let start = 650;
  for (let i = 0; start < track.distance - 500; i++) {
    const length = [300, 270, 330, 260][i % 4];
    corners.push({ start, end: start + length, bend: (i % 2 ? -1 : 1) * strengths[i % strengths.length] * (1 + track.level * 0.12), ramp: 85 });
    start += length + [270, 180, 320, 220][i % 4] - track.level * 35;
  }
  cornerCache.set(track.id, corners);
  return corners;
}
function curveAt(z, trackId) {
  const corner = trackCorners(trackId).find((c) => z >= c.start && z <= c.end);
  if (!corner) return 0;
  const t = clamp(Math.min(z - corner.start, corner.end - z) / corner.ramp, 0, 1);
  return corner.bend * t * t * (3 - 2 * t);
}
function cornerSpeed(curve, handling = 1.1) {
  return Math.sqrt(3e3 * handling / Math.max(0.01, Math.abs(curve)));
}
function cornerPace(z, trackId, handling = 1.1, condition = "sunset", kneePadId) {
  let speed = 120;
  for (let ahead = 0; ahead <= 240; ahead += 20) {
    const safe = cornerSpeed(curveAt(z + ahead, trackId), plannedCornerHandling(handling, kneePadId) * surfaceGrip(trackId, condition));
    speed = Math.min(speed, Math.sqrt(safe * safe + 2 * 19 * surfaceBraking(trackId, condition) * Math.max(0, ahead - 12)));
  }
  return speed;
}
function cornerForces(speed, handling, curve, shoulder = false) {
  const load = speed * speed * Math.abs(curve) / (3e3 * handling);
  const excess = Math.max(0, load - 1);
  return {
    lateral: (2.6 + speed * 0.0625) * handling * (shoulder ? 0.72 : 1) / (1 + excess * 0.9),
    drift: Math.sign(curve) * (4 * load + 4 * excess * excess),
    sliding: excess > 0.2
  };
}

// src/game/guardrails.ts
var GUARD_RAIL_X = 7.75;
var GUARD_RAIL_CLEARANCE = 0.75;
var GUARD_RAIL_LIMIT = GUARD_RAIL_X - GUARD_RAIL_CLEARANCE;
function hasGuardRail(trackId, side) {
  return trackId === "serra" || (trackId === "costa" || trackId === "porto") && side < 0;
}
function roadsideBarrier(trackId, side, z) {
  if (hasGuardRail(trackId, side)) return { limit: GUARD_RAIL_LIMIT, material: "metal" };
  const strength = trackId === "terra" ? bankStrength(z, side) : 0;
  return strength > 0 ? { limit: roadHalf(trackId) + (1 - strength) * 3.5, material: "earth" } : null;
}
function guardRailPosition(trackId, x, z = 0) {
  const side = Math.sign(x), barrier = roadsideBarrier(trackId, side, z);
  return barrier ? side * Math.min(Math.abs(x), barrier.limit) : x;
}
function contactGuardRail(trackId, rider, dt = 0) {
  const x = guardRailPosition(trackId, rider.x, rider.z), penetration = Math.abs(rider.x - x);
  if (!penetration) return false;
  rider.x = x;
  rider.speed = Math.max(0, rider.speed - penetration * 6 - dt * 12);
  return true;
}

// src/game/recovery.ts
var RUN_SPEED = 7.2;
var MOUNT_DISTANCE = 1.35;
var MOUNT_SECONDS = 0.65;
var EXPLOSION_SECONDS = 1.8;
var reachableX = (s, x, z) => guardRailPosition(s.trackId, clamp(x, -lateralLimit(s.trackId) + 0.5, lateralLimit(s.trackId) - 0.5), z);
var move = (v, drag, dt) => Math.sign(v) * Math.max(0, Math.abs(v) - drag * dt);
function beginRecovery(s, r, kind = "spill") {
  const speed = clamp(r.speed, 0, 80), side = r.lean < 0 ? -1 : 1;
  r.recovery = { origin: { x: r.x, z: r.z, speed: r.speed, lean: r.lean }, phase: "sliding", bikeX: r.x, bikeZ: r.z, bikeVX: r.lean * 1.5, bikeVZ: speed * (kind === "impact" ? 0.2 : 0.8), vx: r.lean * 1.5, vz: Math.min(35, speed * 0.58), timer: 0, age: 0, cycle: 0, facingX: 0, facingZ: 1, hitCooldown: 0.65, hits: 0 };
  r.x = reachableX(s, r.x + side * 0.7, r.z);
  r.crash = 1e-3;
  r.speed = 0;
  r.health = Math.max(24, r.health);
  r.lean = 0;
}
function recoveryCommand(r) {
  const f = r.recovery;
  if (!f) return { throttle: 0, brake: 0, steer: 0, attack: null };
  const dx = f.bikeX - r.x, dz = f.bikeZ - r.z, len = Math.max(1, Math.hypot(dx, dz));
  return { throttle: Math.max(0, dz / len), brake: Math.max(0, -dz / len), steer: clamp(dx / len, -1, 1), attack: null };
}
function advanceRecovery(s, r, cmd, dt, confirm = true) {
  const f = r.recovery;
  if (!f) return;
  f.age += dt;
  f.hitCooldown = Math.max(0, f.hitCooldown - dt);
  r.crash = 1e-3;
  r.speed = 0;
  r.attack = null;
  if (f.phase === "exploding") {
    f.timer = Math.max(0, f.timer - dt);
    r.z = clamp(r.z + f.vz * dt, 0, getTrack(s.trackId).distance + 35);
    r.x = reachableX(s, r.x + f.vx * dt, r.z);
    f.vx = move(f.vx, 5, dt);
    f.vz = move(f.vz, 5, dt);
    return;
  }
  const wet = s.condition === "rain", ground = s.trackId === "terra";
  const bikeDrag = (ground ? 12 : 10) * (wet ? 0.8 : 1), bodyDrag = (ground ? 13 : 12) * (wet ? 0.82 : 1);
  const bx = f.bikeX + f.bikeVX * dt, bz = f.bikeZ + f.bikeVZ * dt;
  f.bikeX = reachableX(s, bx, bz);
  f.bikeZ = clamp(bz, 0, getTrack(s.trackId).distance + 35);
  if (Math.abs(bx - f.bikeX) > 1e-3) f.bikeVX = 0;
  f.bikeVX = move(f.bikeVX, bikeDrag, dt);
  f.bikeVZ = move(f.bikeVZ, bikeDrag, dt);
  if (f.phase === "sliding") {
    const x = r.x + f.vx * dt;
    r.z = clamp(r.z + f.vz * dt, 0, getTrack(s.trackId).distance + 35);
    r.x = reachableX(s, x, r.z);
    if (Math.abs(x - r.x) > 1e-3) f.vx = 0;
    f.vx = move(f.vx, bodyDrag, dt);
    f.vz = move(f.vz, bodyDrag, dt);
    if (confirm && Math.hypot(f.vx, f.vz) < 0.15) {
      f.phase = "gettingUp";
      f.timer = 0.75;
    }
  } else if (f.phase === "gettingUp") {
    f.timer = Math.max(0, f.timer - dt);
    if (confirm && f.timer === 0) f.phase = "walking";
  } else if (f.phase === "walking") {
    if (!confirm && Math.hypot(r.x - f.bikeX, r.z - f.bikeZ) <= MOUNT_DISTANCE && Math.hypot(f.bikeVX, f.bikeVZ) < 0.2) return;
    const dz = clamp(cmd.throttle - cmd.brake, -1, 1), dx = clamp(cmd.steer, -1, 1), norm = Math.max(1, Math.hypot(dx, dz));
    if (Math.hypot(dx, dz) > 0.05) {
      f.facingX = dx / norm;
      f.facingZ = dz / norm;
      f.cycle += dt * 9 * Math.hypot(dx, dz) / norm;
    }
    r.z = clamp(r.z + RUN_SPEED * dt * dz / norm, 0, getTrack(s.trackId).distance + 35);
    r.x = reachableX(s, r.x + RUN_SPEED * dt * dx / norm, r.z);
    if (confirm && Math.hypot(r.x - f.bikeX, r.z - f.bikeZ) <= MOUNT_DISTANCE && Math.hypot(f.bikeVX, f.bikeVZ) < 0.2) {
      if (r.integrity <= 0) explodeBike(s, r);
      else {
        f.phase = "mounting";
        f.timer = MOUNT_SECONDS;
      }
    }
  } else {
    if (r.integrity <= 0) {
      if (confirm) explodeBike(s, r);
      return;
    }
    f.timer = Math.max(0, f.timer - dt);
    r.x += (f.bikeX - r.x) * Math.min(1, dt * 9);
    r.z += (f.bikeZ - r.z) * Math.min(1, dt * 9);
    if (confirm && f.timer === 0) {
      r.x = f.bikeX;
      r.z = f.bikeZ;
      r.speed = 0;
      r.crash = 0;
      r.immune = 1.1;
      delete r.recovery;
      s.events.push({ type: "pass", actor: r.id, text: "DE VOLTA \xC0 MOTO!" });
    }
  }
}
function explodeBike(s, r) {
  const f = r.recovery;
  f.phase = "exploding";
  f.timer = EXPLOSION_SECONDS;
  f.bikeVX = 0;
  f.bikeVZ = 0;
  f.vx = (r.x < f.bikeX ? -1 : 1) * 3;
  f.vz = r.z < f.bikeZ ? -3 : 3;
  f.hitCooldown = EXPLOSION_SECONDS;
  s.events.push({ type: "explosion", actor: r.id, text: "A MOTO EXPLODIU!" });
}
function hitPedestrian(s, r, source, speed, pushX) {
  const f = r.recovery;
  if (!f || f.phase === "exploding" || f.hitCooldown > 0 || r.out) return false;
  f.origin = { x: r.x, z: r.z, speed: 0, lean: pushX };
  f.hitCooldown = 1.4;
  f.hits++;
  f.phase = "sliding";
  f.timer = 0;
  f.vz = Math.sign(speed) * clamp(Math.abs(speed) * 0.12, 2, 7);
  f.vx = clamp(pushX, -1, 1) * 1.5;
  r.health = Math.max(1, r.health - clamp(9 + Math.abs(speed) * 0.24, 12, 27));
  s.events.push({ type: "hit", actor: source, target: r.id, text: r.id === "player" ? "ATROPELADO!" : void 0 });
  return true;
}

// src/game/helmets.ts
var HELMETS = [
  { id: "integral", name: "Integral", price: 0, description: "Casco fechado, linhas cl\xE1ssicas e faixa central." },
  { id: "retro", name: "Retr\xF4", price: 1500, description: "Casco arredondado e \xF3culos com tira de couro." },
  { id: "cross", name: "Cross", price: 3e3, description: "Pala larga, \xF3culos escuros e queixeira alongada." },
  { id: "racing", name: "Racing", price: 5e3, description: "Perfil angular, entradas de ar e spoiler traseiro." }
];
var HELMET_COLORS = [
  { id: "white", name: "Branco", color: "#e4e9dc" },
  { id: "black", name: "Preto", color: "#424d5a" },
  { id: "red", name: "Vermelho", color: "#ed6557" },
  { id: "orange", name: "Laranja", color: "#f39c48" },
  { id: "yellow", name: "Amarelo", color: "#f1d955" },
  { id: "green", name: "Verde", color: "#96db69" },
  { id: "blue", name: "Azul", color: "#62a9ed" },
  { id: "purple", name: "Roxo", color: "#ba8fe4" }
];
function getHelmet(id) {
  return HELMETS.find((h) => h.id === id) ?? HELMETS[0];
}
function getHelmetColor(id) {
  return HELMET_COLORS.find((c) => c.id === id) ?? HELMET_COLORS[0];
}
function ownsHelmet(save, id) {
  return id === "integral" || !!save?.ownedHelmets?.includes(id);
}
function equippedHelmet(save) {
  const helmet = getHelmet(save?.helmetId);
  return ownsHelmet(save, helmet.id) ? helmet : HELMETS[0];
}

// src/game/weapons.ts
var WEAPONS = [
  { id: "bottle", name: "Garrafa", price: 650, damage: 24, reach: 2.7, longitudinal: 4.8, windup: 0.12, duration: 0.34, cooldown: 0.5, push: 0.35, action: "GARRAFADA", description: "R\xE1pida e de curto alcance. Boa para golpes seguidos." },
  { id: "bat", name: "Bast\xE3o de beisebol", price: 1500, damage: 38, reach: 3.4, longitudinal: 5.7, windup: 0.23, duration: 0.5, cooldown: 0.78, push: 0.75, action: "BASTONADA", description: "O golpe mais forte. Exige chegar perto e acertar o tempo." },
  { id: "chain", name: "Corrente", price: 2400, damage: 32, reach: 4.5, longitudinal: 6.2, windup: 0.3, duration: 0.64, cooldown: 0.94, push: 0.55, action: "CORRENTADA", description: "Maior alcance, com mais tempo entre os golpes." }
];
function getWeapon(id) {
  return WEAPONS.find((w) => w.id === id);
}
function equippedWeapon(save) {
  return save?.ownedWeapons?.includes(save.weaponId ?? "") ? getWeapon(save.weaponId) : void 0;
}

// src/game/stunts.ts
var WHEELIE_USES = 3;
var WHEELIE_DURATION = 2.4;
var WHEELIE_MIN_SPEED = 20;
var JUMP_DURATION = 1;
var wheeliesLeft = (r) => r.wheeliesLeft ?? WHEELIE_USES;
var stunting = (r) => (r.wheelieTime ?? 0) > 0 || (r.jumpTime ?? 0) > 0;
function jumpHeight(r) {
  return !(r.jumpTime > 0) || r.crash || r.out || r.finishedAt !== null ? 0 : Math.max(0, Math.sin(Math.PI * (1 - (r.jumpTime ?? 0) / JUMP_DURATION))) * 2.2;
}
function cancelStunt(r) {
  r.wheelieTime = 0;
  r.jumpTime = 0;
  r.jumpTarget = void 0;
}
function launch(rider, target) {
  rider.wheelieTime = 0;
  rider.jumpTime = JUMP_DURATION;
  rider.jumpTarget = target;
  rider.attack = null;
  rider.kneeTime = 0;
  rider.wetKneeTicks = 0;
}
function advanceStunt(state, rider, command, dt) {
  if (rider.jumpTime) {
    rider.jumpTime = Math.max(0, rider.jumpTime - dt);
    if (!rider.jumpTime) rider.jumpTarget = void 0;
  }
  if (rider.crash || rider.out || rider.finishedAt !== null) return;
  if (!(rider.jumpTime > 0) && rider.speed >= 8) {
    const fallen = state.riders.find((other) => other.id !== rider.id && other.recovery && other.recovery.bikeZ >= rider.z && other.recovery.bikeZ - rider.z <= 2 + rider.speed * dt && Math.abs(other.recovery.bikeX - rider.x) < 1.65);
    if (fallen) {
      launch(rider, `fallen:${fallen.id}:${fallen.falls}`);
      return;
    }
    const ramp2 = state.obstacles.find((o) => isRamp(o) && o.z >= rider.z && o.z - rider.z <= 1.5 + rider.speed * dt && Math.abs(o.x - rider.x) < obstacleShape(o).contact);
    if (ramp2) {
      launch(rider, ramp2.id);
      return;
    }
  }
  if (!rider.wheelieTime) return;
  rider.wheelieTime = Math.max(0, rider.wheelieTime - dt);
  if (command.brake > 0.2 || rider.speed < WHEELIE_MIN_SPEED || Math.abs(rider.x) > roadHalf(state.trackId)) rider.wheelieTime = 0;
  if (!rider.wheelieTime) return;
  const targets = [
    ...state.traffic.filter((t) => t.kind === "car" && t.speed < 0 && Math.abs(t.x - rider.x) < 1.7),
    ...state.obstacles.filter((o) => o.kind === "fallenTree" && Math.abs(o.x - rider.x) < obstacleShape(o).contact)
  ];
  const target = targets.map((t) => ({ t, ttc: (t.z - rider.z) / (rider.speed - ("speed" in t ? t.speed : 0)) })).filter(({ ttc }) => ttc >= 0.16 && ttc <= 0.38).sort((a, b) => a.ttc - b.ttc)[0]?.t;
  if (!target) return;
  launch(rider, target.id);
}
function clearsObstacle(rider, obstacle) {
  if (isRamp(obstacle)) return true;
  if (obstacle.kind === "fallenTree") return rider.jumpTarget === obstacle.id && (rider.jumpTime ?? 0) > 0 && jumpHeight(rider) > 1.1;
  return (obstacle.kind === "armadillo" || obstacle.kind === "tumbleweed") && jumpHeight(rider) > 0.65;
}
function clearsCar(rider, traffic) {
  return traffic.kind === "car" && traffic.speed < 0 && rider.jumpTarget === traffic.id && (rider.jumpTime ?? 0) > 0 && jumpHeight(rider) > 1.1;
}

// src/game/banter.ts
var TAUNTS = [
  "Ningu\xE9m me pega!",
  "Eu sou o melhor!",
  "Come poeira!",
  "Ficou pra tr\xE1s!",
  "T\xE1 passeando?",
  "Essa estrada \xE9 minha!",
  "Quero ver acompanhar!",
  "Hoje eu levo essa!",
  "Sai da frente!",
  "S\xF3 vai ver minha placa!"
];
function pick(seed, count) {
  let hash = 2166136261;
  for (const char of seed) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return (hash >>> 0) % count;
}
function sayTaunt(state, rider) {
  if (rider.crash || rider.out || rider.finishedAt !== null || (rider.tauntReadyAt ?? 0) > state.time) return;
  const seq = (rider.tauntSeq ?? 0) + 1, old = rider.speech?.index;
  let index = pick(`${rider.id}/${state.tick}/${seq}`, TAUNTS.length);
  if (index === old) index = (index + 1) % TAUNTS.length;
  rider.speech = { index, until: state.time + 3 };
  rider.tauntReadyAt = state.time + 5;
  rider.tauntSeq = seq;
}
function advanceBanter(state) {
  if (state.time < (state.nextTauntAt ?? 12)) return;
  state.nextTauntAt = state.time + 10 + pick(`${state.tick}/${state.trackId}`, 8);
  const humans = state.riders.filter((r) => r.profile === "player" && !r.out);
  const rivals = state.riders.filter((r) => r.profile !== "player" && r.profile !== "police" && !r.crash && !r.out && r.finishedAt === null && humans.some((h) => Math.abs(h.z - r.z) < 100));
  if (rivals.length) sayTaunt(state, rivals[pick(String(state.tick), rivals.length)]);
}

// src/game/types.ts
var EMPTY_COMMAND = { throttle: 0, brake: 0, steer: 0, attack: null };

// src/game/simulation.ts
var STEP = 1 / 60;
var FALL_ARREST_RADIUS = 30;
var POLICE_TOP_SPEED = (Math.max(...BIKES.map((b) => b.speed)) + 3 * 2.5) * NITRO_MULTIPLIER + 4;
var ATTACKS = {
  punch: { windup: 0.13, duration: 0.34, cooldown: 0.46, reach: 2.3, longitudinal: 4.8, damage: 16, push: 0.35 },
  kick: { windup: 0.25, duration: 0.52, cooldown: 0.8, reach: 2.6, longitudinal: 4.6, damage: 22, push: 1.1 },
  weapon: { windup: 0.21, duration: 0.48, cooldown: 0.72, reach: 3.6, longitudinal: 5.7, damage: 30, push: 0.55 }
};
function attackSpec(rider, kind) {
  return kind === "weapon" ? getWeapon(rider.weaponId) ?? ATTACKS.weapon : ATTACKS[kind];
}
function random(state) {
  let n = state.rng;
  n ^= n << 13;
  n ^= n >>> 17;
  n ^= n << 5;
  state.rng = n >>> 0;
  return state.rng / 4294967296;
}
function makeRider(id, name, profile, color, x, z) {
  return { id, name, profile, color, bikeId: "ferro", x, z, speed: 0, lean: 0, health: 100, integrity: 100, maxSpeed: 55, acceleration: 10, handling: 1, armor: 1, weapon: false, wheeliesLeft: WHEELIE_USES, attack: null, cooldown: 0, crash: 0, immune: 0, targetX: x, decisionAt: 0, finishedAt: null, hits: 0, falls: 0 };
}
function stockBike(id) {
  const bike = getBike(id);
  return { bikeId: bike.id, maxSpeed: bike.speed, acceleration: bike.acceleration, handling: bike.handling, armor: bike.armor };
}
function rivalKneePad(bikeId, profile, level) {
  if (!supportsKneeDown(bikeId) || profile !== "fast" && profile !== "careful") return void 0;
  return profile === "fast" && level >= 2 ? "purple" : level >= 1 ? "blue" : "green";
}
function createRace(trackId = "costa", save, seed = 88117, condition = "sunset") {
  const bike = getBike(save?.bikeId);
  const up = save?.upgrades[bike.id] ?? { engine: 0, armor: 0, handling: 0 };
  const player = makeRider("player", "VOC\xCA", "player", bike.color, 1.7, 0);
  player.helmetId = equippedHelmet(save).id;
  player.helmetColorId = getHelmetColor(save?.helmetColorId).id;
  const weapon = equippedWeapon(save);
  if (weapon) player.weaponId = weapon.id;
  const pad = equippedKneePad(save);
  if (pad) player.kneePadId = pad.id;
  const nitro = nitroCount(bike.id, save?.nitro?.[bike.id]);
  if (nitro) player.nitro = nitro;
  Object.assign(player, { bikeId: bike.id, maxSpeed: bike.speed + up.engine * 2.5, acceleration: bike.acceleration + up.engine * 0.7, handling: bike.handling + up.handling * 0.1, armor: bike.armor + up.armor * 0.15, integrity: save?.condition[bike.id] ?? 100, weapon: true });
  const names = ["NINA", "COBRA", "DANTE", "LUNA", "ROCHA", "FA\xCDSCA", "ZECA"];
  const colors = ["#d87bfa", "#f28451", "#6cdace", "#ebbc5c", "#a4bde2", "#ef6f8a", "#e7e6dc"];
  const profiles = ["aggressive", "fast", "careful", "aggressive", "careful", "fast", "aggressive"];
  const riders = [player, ...names.map((name, i) => {
    const r = makeRider(`rival-${i}`, name, profiles[i], colors[i], i % 2 ? -1.5 : 3.8, 7 + i * 9);
    r.helmetId = HELMETS[i % HELMETS.length].id;
    r.helmetColorId = HELMET_COLORS[(i + 2) % HELMET_COLORS.length].id;
    Object.assign(r, stockBike(BIKES[(i + 1) % BIKES.length].id));
    r.maxSpeed *= 0.98 + getTrack(trackId).level * 0.01;
    const pad2 = rivalKneePad(r.bikeId, r.profile, getTrack(trackId).level);
    if (pad2) r.kneePadId = pad2;
    r.weapon = i === 1 || i === 3 || i === 6;
    return r;
  })];
  const state = { version: 1, condition: raceCondition(condition), scenicEvent: coastalEvent(trackId, seed), tick: 0, rng: seed || 1, trackId, mode: "countdown", countdown: 3.5, time: 0, riders, traffic: [], obstacles: [], events: [], collisions: {}, heat: 0, capture: 0, policeActive: false, result: null };
  const length = getTrack(trackId).distance;
  for (let z = 400, i = 0; z < length + 1800; z += 230 + random(state) * 160, i++) {
    const oncoming = i % 3 === 1;
    state.traffic.push({ id: `traffic-${i}`, x: (oncoming ? -1 : 1) * (i % 2 ? 1.75 : 5.25), z, speed: oncoming ? -18 - random(state) * 6 : 19 + random(state) * 9, color: ["#cdbc9b", "#a8b7c0", "#de785f", "#dcd7bb", "#679d9d"][i % 5], kind: i % 4 === 2 ? "van" : "car" });
  }
  for (let z = 1150, i = 0; z < length - 180; z += 630 - getTrack(trackId).level * 70, i++) {
    state.obstacles.push({ id: `obstacle-${i}`, x: i % 3 === 0 ? 4.8 : i % 3 === 1 ? -3.2 : 6.2, z, kind: i % 3 === 1 ? "barrier" : "oil" });
  }
  if (trackId === "porto") {
    state.traffic = portTraffic(() => random(state));
    state.obstacles = portObstacles();
    state.scenicEvent = portPassengerEvent(seed, state.traffic);
  }
  if (trackId === "terra") {
    state.traffic = ruralTraffic(() => random(state));
    state.obstacles = ruralObstacles(state.condition);
    state.scenicEvent = ruralEvent(seed, state.condition);
    riders.forEach((r, i) => {
      r.x = i % 2 ? -2.1 : 2.1;
      r.targetX = r.x;
      r.z = -Math.floor(i / 2) * 10;
    });
  }
  const additions = trackHazards(trackId, seed);
  state.obstacles = state.obstacles.filter((o) => !additions.some((a) => !a.motion && Math.abs(a.z - o.z) < 100));
  state.obstacles.push(...additions);
  for (const o of state.obstacles) if (o.motion) o.x = obstacleX(o, state.time);
  return state;
}
function ranking(state) {
  return state.riders.filter((r) => r.profile !== "police").slice().sort((a, b) => {
    if (a.finishedAt !== null && b.finishedAt !== null) return a.finishedAt - b.finishedAt;
    if (a.finishedAt !== null) return -1;
    if (b.finishedAt !== null) return 1;
    if (!!a.out !== !!b.out) return a.out ? 1 : -1;
    return b.z - a.z || a.id.localeCompare(b.id);
  });
}
function nearestTarget(state, rider, kind = "weapon") {
  if ((rider.jumpTime ?? 0) > 0) return void 0;
  const info = attackSpec(rider, kind);
  return state.riders.filter((r) => r.id !== rider.id && !(r.jumpTime > 0) && !r.out && !r.crash && !r.immune && r.finishedAt === null && Math.abs(r.z - rider.z) < info.longitudinal && Math.abs(r.x - rider.x) < info.reach).sort((a, b) => Math.abs(a.z - rider.z) + Math.abs(a.x - rider.x) - Math.abs(b.z - rider.z) - Math.abs(b.x - rider.x))[0];
}
function crashRider(state, rider, force = false, kind = "spill") {
  if (rider.crash || rider.immune && !force) return;
  beginRecovery(state, rider, kind);
  rider.integrity = Math.max(0, rider.integrity - 13 / rider.armor);
  rider.attack = null;
  rider.kneeTime = 0;
  rider.wetKneeTicks = 0;
  rider.nitroTime = 0;
  rider.speech = void 0;
  cancelStunt(rider);
  rider.falls++;
  state.events.push({ type: "crash", actor: rider.id, text: "NO CH\xC3O! VOLTE AT\xC9 A MOTO" });
}
function performAction(state, rider, action) {
  if (state.mode !== "racing" || rider.out || rider.crash || rider.finishedAt !== null) return;
  if (action === "wheelie") {
    if (stunting(rider) || wheeliesLeft(rider) <= 0 || rider.speed < WHEELIE_MIN_SPEED || Math.abs(rider.x) > roadHalf(state.trackId) || rider.immune) return;
    rider.wheeliesLeft = wheeliesLeft(rider) - 1;
    rider.wheelieTime = WHEELIE_DURATION;
    rider.kneeTime = 0;
    rider.wetKneeTicks = 0;
  } else if (action === "kneeLeft" || action === "kneeRight") {
    if (stunting(rider)) return;
    if (!getKneePad(rider.kneePadId) || !supportsKneeDown(rider.bikeId) || rider.speed < 20 || Math.abs(rider.x) > roadHalf(state.trackId)) return;
    const side = action === "kneeLeft" ? -1 : 1;
    if ((rider.kneeTime ?? 0) > 0 && rider.kneeSide === side) return;
    rider.kneeSide = side;
    rider.kneeTime = KNEE_DURATION;
  } else if (action === "nitro") {
    if (!(rider.nitro > 0) || (rider.nitroTime ?? 0) > 0) return;
    rider.nitro--;
    rider.nitroUsed = (rider.nitroUsed ?? 0) + 1;
    rider.nitroTime = NITRO_DURATION;
    state.events.push({ type: "nitro", actor: rider.id });
  } else if (action === "horn") {
    if ((rider.hornCooldown ?? 0) > 0) return;
    rider.hornCooldown = 1;
    state.events.push({ type: "horn", actor: rider.id });
  } else if (action === "taunt") sayTaunt(state, rider);
}
function impact(state, rider, damage, push) {
  if (rider.immune || rider.crash) return;
  rider.health = Math.max(0, rider.health - damage);
  rider.x = clamp(rider.x + push, -lateralLimit(state.trackId), lateralLimit(state.trackId));
  contactGuardRail(state.trackId, rider);
  rider.speed *= 0.94;
  if (rider.health <= 0) crashRider(state, rider);
}
function botCommand(state, rider) {
  if (rider.recovery && !rider.out) return recoveryCommand(rider);
  if (rider.out || rider.crash || rider.finishedAt !== null) return EMPTY_COMMAND;
  const police = rider.profile === "police";
  const player = police ? policeTarget(state, rider) : state.riders.filter((r) => r.id !== rider.id && r.profile !== "police" && !r.out && r.finishedAt === null).sort((a, b) => Math.abs(a.z - rider.z) - Math.abs(b.z - rider.z))[0];
  if (!player) return { ...EMPTY_COMMAND, brake: 1 };
  if (state.time >= rider.decisionAt) {
    rider.decisionAt = state.time + 0.55 + random(state) * 0.7;
    rider.targetX = police ? player.x : (random(state) > 0.23 ? 1 : -1) * (1.4 + random(state) * 3.6);
    if (rider.profile === "aggressive" && Math.abs(rider.z - player.z) < 24) rider.targetX = player.x + (rider.x < player.x ? -1.7 : 1.7);
  }
  const inside = state.trackId === "terra" ? 3 : 5.5;
  let target = state.trackId === "terra" ? clamp(rider.targetX, -inside, inside) : rider.targetX;
  let brake = 0;
  const dangers = [...state.traffic, ...state.obstacles].filter((t) => t.z - rider.z > -7 && t.z - rider.z < Math.max(30 + rider.speed * 1.5, "width" in t && (t.width ?? 0) > 4 ? 220 : 0));
  if (dangers.some((t) => Math.min(Math.abs(t.x - rider.x), Math.abs(t.x - target)) < dangerClearance(state.trackId, t))) {
    const candidates = roadLanes(state.trackId).slice();
    const cost = (lane) => Math.abs(lane - rider.x) * 0.35 + dangers.reduce((sum, t) => sum + (Math.abs(t.x - lane) < dangerClearance(state.trackId, t) ? 30 - Math.max(0, t.z - rider.z) * 0.04 : 0), 0);
    target = candidates.sort((a, b) => cost(a) - cost(b))[0];
    rider.targetX = target;
    if (dangers.some((t) => t.z - rider.z < rider.speed * 0.4 && Math.abs(t.x - rider.x) < dangerClearance(state.trackId, t, true))) brake = 0.7;
  }
  for (const other of state.riders) {
    if (other.id === rider.id) continue;
    if (other.z - rider.z > 0 && other.z - rider.z < 14 && Math.abs(other.x - rider.x) < 1.05) {
      const passing = clamp(other.x + (rider.x < other.x ? -2 : 2), -inside, inside);
      if (!dangers.some((t) => Math.abs(t.x - passing) < dangerClearance(state.trackId, t))) target = passing;
    }
  }
  let attack = null;
  const nearby = nearestTarget(state, rider, rider.weapon ? "weapon" : "punch");
  if (nearby && rider.cooldown === 0 && (rider.profile !== "careful" || state.tick % 80 < 8)) attack = rider.weapon ? "weapon" : rider.profile === "aggressive" ? "kick" : "punch";
  const curve = curveAt(rider.z, state.trackId);
  const kneeCapable = !police && raceCondition(state.condition) !== "rain" && supportsKneeDown(rider.bikeId) && !!getKneePad(rider.kneePadId);
  const forces = cornerForces(rider.speed, cornerHandling(rider, curve, state.trackId) * surfaceGrip(state.trackId, state.condition), curve, Math.abs(rider.x) > roadHalf(state.trackId));
  const steering = clamp((target - rider.x) * 0.9 + forces.drift / forces.lateral, -1, 1);
  const canLean = kneeCapable && steering * Math.sign(curve) >= -0.2 && Math.abs(rider.x) <= roadHalf(state.trackId) && !stunting(rider);
  const action = canLean && !(rider.kneeTime > 0) && rider.speed >= 24 && Math.abs(curve) > 0.5 ? curve > 0 ? "kneeRight" : "kneeLeft" : void 0;
  const pace = cornerPace(rider.z, state.trackId, rider.handling, state.condition, canLean ? rider.kneePadId : void 0) * (police ? 0.98 : rider.profile === "careful" ? 0.95 : rider.profile === "fast" ? 1.04 : 0.99);
  brake = Math.max(brake, clamp((rider.speed - pace) * 0.3, 0, 1));
  if (police && rider.z > player.z + 7) brake = Math.max(brake, 0.42);
  return { throttle: rider.speed > pace - 0.6 || brake > 0.1 ? 0 : 1, brake, steer: steering, attack, ...action ? { action } : {} };
}
function policeTarget(state, officer) {
  return state.riders.filter((r) => r.id !== officer.id && r.profile !== "police" && !r.out && r.finishedAt === null).sort((a, b) => Math.hypot(a.z - officer.z, a.x - officer.x) - Math.hypot(b.z - officer.z, b.x - officer.x) || a.id.localeCompare(b.id))[0];
}
function applyCommand(state, rider, command) {
  if (rider.recovery && !rider.out) {
    advanceRecovery(state, rider, command, STEP);
    return;
  }
  contactGuardRail(state.trackId, rider);
  if (rider.out) {
    rider.speed = 0;
    rider.attack = null;
    return;
  }
  rider.cooldown = Math.max(0, rider.cooldown - STEP);
  rider.immune = Math.max(0, rider.immune - STEP);
  if (rider.hornCooldown) rider.hornCooldown = Math.max(0, rider.hornCooldown - STEP);
  if (rider.kneeTime) rider.kneeTime = Math.max(0, rider.kneeTime - STEP);
  if (rider.nitroTime) rider.nitroTime = Math.max(0, rider.nitroTime - STEP);
  advanceStunt(state, rider, command, STEP);
  if (command.action) performAction(state, rider, command.action);
  if (rider.finishedAt !== null) {
    rider.speed = Math.max(0, rider.speed - STEP * 12);
    return;
  }
  if (rider.crash > 0) {
    rider.crash = Math.max(0, rider.crash - STEP);
    rider.speed *= 0.975;
    rider.z += rider.speed * STEP;
    if (rider.crash === 0) {
      rider.health = 100;
      rider.immune = 2.4;
      rider.x = clamp(rider.x, -roadHalf(state.trackId) + 1.6, roadHalf(state.trackId) - 1.6);
      rider.speed = 12;
    }
    return;
  }
  const onShoulder = Math.abs(rider.x) > roadHalf(state.trackId);
  if (rider.kneeTime && (onShoulder || rider.speed < 20 || command.steer * (rider.kneeSide ?? 0) < -0.2)) rider.kneeTime = 0;
  const curve = curveAt(rider.z, state.trackId);
  rider.wetKneeTicks = raceCondition(state.condition) === "rain" && kneeContact(rider, curve, state.trackId) ? (rider.wetKneeTicks ?? 0) + 1 : 0;
  const boost = (rider.nitroTime ?? 0) > 0 ? NITRO_MULTIPLIER : 1;
  const topSpeed = rider.maxSpeed * boost;
  const shoulderLimit = Math.abs(curve) > 0.8 ? 0.38 : 0.56;
  const max = topSpeed * (onShoulder ? shoulderLimit : 1) * (0.92 + rider.integrity / 1250);
  const acceleration = command.throttle * rider.acceleration * boost * (onShoulder ? 0.55 : 1) * (1 - 0.35 * rider.speed / topSpeed);
  rider.speed = clamp(rider.speed + (acceleration - command.brake * 29 * surfaceBraking(state.trackId, state.condition) - (command.throttle ? 1.2 : 3.6) - surfaceDrag(state.trackId, state.condition) - (state.trackId === "terra" ? 9.8 * ruralSlope(rider.z) : 0)) * STEP, 0, Math.max(rider.speed, topSpeed));
  if (rider.speed > max) rider.speed = Math.max(max, rider.speed - STEP * (onShoulder ? 34 : 4));
  const steering = clamp(command.steer, -1, 1);
  const forces = cornerForces(rider.speed, cornerHandling(rider, curve, state.trackId) * surfaceGrip(state.trackId, state.condition), curve, onShoulder);
  rider.x = clamp(rider.x + (steering * forces.lateral - forces.drift) * STEP, -lateralLimit(state.trackId), lateralLimit(state.trackId));
  contactGuardRail(state.trackId, rider, STEP);
  rider.lean += (steering * 0.32 - rider.lean) * 0.12;
  rider.z += rider.speed * STEP;
  if (state.trackId === "terra") contactGuardRail(state.trackId, rider);
  rider.health = Math.min(100, rider.health + STEP * 1.15);
  if (Math.abs(rider.x) > lateralLimit(state.trackId) - 0.7 && rider.speed > 26 && !rider.immune) {
    rider.integrity -= STEP * 2.2;
  }
  if (command.attack && !(rider.jumpTime > 0) && !rider.attack && rider.cooldown === 0 && (command.attack !== "weapon" || rider.weapon)) {
    const target = nearestTarget(state, rider, command.attack);
    rider.attack = { kind: command.attack, age: 0, side: target ? Math.sign(target.x - rider.x) || 1 : Math.sign(steering) || 1, hit: false };
    rider.cooldown = attackSpec(rider, command.attack).cooldown + (rider.profile === "player" ? 0 : 0.35);
    state.events.push({ type: "attack", actor: rider.id });
  }
}
function resolveAttacks(state) {
  for (const rider of state.riders) {
    const attack = rider.attack;
    if (!attack) continue;
    const spec = attackSpec(rider, attack.kind);
    const telegraph = rider.profile === "player" ? 0 : 0.25;
    attack.age += STEP;
    if (attack.age >= spec.windup + telegraph && !attack.hit) {
      attack.hit = true;
      const target = nearestTarget(state, rider, attack.kind);
      if (target && (Math.sign(target.x - rider.x) === attack.side || Math.abs(target.x - rider.x) < 0.4)) {
        impact(state, target, spec.damage, attack.side * spec.push);
        rider.hits++;
        const action = attack.kind === "kick" ? "CHUTE" : attack.kind === "weapon" ? getWeapon(rider.weaponId)?.action ?? "BASTONADA" : "SOCO";
        state.events.push({ type: "hit", actor: rider.id, target: target.id, text: target.id === "player" ? `VOC\xCA LEVOU ${action} \xB7 ${rider.name}` : `${target.name} \xB7 ${action}!` });
        if (rider.profile === "player") state.heat = clamp(state.heat + 12, 0, 100);
        if (attack.kind === "punch" && target.weapon && !getWeapon(target.weaponId)) {
          target.weapon = false;
          rider.weapon = true;
          state.events.push({ type: "steal", actor: rider.id, text: "BAST\xC3O TOMADO!" });
        }
      }
    }
    if (attack.age >= spec.duration + telegraph) rider.attack = null;
  }
}
function mayCollide(state, a, b, cooldown = 1.4) {
  const key = [a, b].sort().join(":");
  if ((state.collisions[key] ?? -99) + cooldown > state.time) return false;
  state.collisions[key] = state.time;
  return true;
}
function resolveCollisions(state, oldZ) {
  for (const r of state.riders) {
    if (r.out || r.crash || r.immune || r.finishedAt !== null) continue;
    for (const t of state.traffic) {
      if (clearsCar(r, t)) continue;
      const relBefore = t.z - t.speed * STEP - (oldZ.get(r.id) ?? r.z);
      const relNow = t.z - r.z;
      if ((Math.abs(relNow) < trafficShape(state.trackId, t.kind).length || relBefore * relNow < 0) && Math.abs(t.x - r.x) < trafficShape(state.trackId, t.kind).contact && mayCollide(state, r.id, t.id)) {
        r.integrity = Math.max(0, r.integrity - (t.speed < 0 ? 22 : 14) / r.armor);
        crashRider(state, r, false, "impact");
      }
    }
    for (const o of state.obstacles) {
      if (r.crash || clearsObstacle(r, o)) continue;
      const shape = obstacleShape(o), before = o.z - (oldZ.get(r.id) ?? r.z), after = o.z - r.z;
      if ((Math.abs(after) < shape.length || before * after < 0) && Math.abs(o.x - r.x) < shape.contact && mayCollide(state, r.id, o.id, 3)) {
        if (o.kind === "cone") {
          r.speed *= 0.9;
          r.health = Math.max(1, r.health - 4);
          state.events.push({ type: "hit", actor: o.id, text: "CONE \xB7 PERDEU VELOCIDADE" });
        } else if (o.kind === "tumbleweed") {
          r.speed *= 0.96;
          state.events.push({ type: "hit", actor: r.id, text: "FENO NA PISTA" });
        } else if (o.kind === "armadillo") {
          crashRider(state, r);
          state.events[state.events.length - 1].text = "TATU NA PISTA \xB7 QUEDA!";
        } else if (o.kind === "gravel" || o.kind === "mud") {
          r.speed *= o.kind === "mud" ? 0.78 : 0.85;
          state.events.push({ type: "hit", actor: o.id, text: o.kind === "mud" ? "LAMA \xB7 PERDEU TRA\xC7\xC3O" : "CASCALHO \xB7 PERDEU TRA\xC7\xC3O" });
        } else if (o.kind === "oil") {
          impact(state, r, 23, r.x < 0 ? -0.8 : 0.8);
          r.speed *= 0.64;
          state.events.push({ type: "hit", actor: o.id, text: "\xD3LEO \xB7 SEM ADER\xCANCIA" });
        } else {
          r.integrity = Math.max(0, r.integrity - 15 / r.armor);
          crashRider(state, r, false, "impact");
        }
      }
    }
    for (const other of state.riders) {
      if (other.id <= r.id || other.out || other.crash || other.immune || other.finishedAt !== null) continue;
      if (Math.abs(other.z - r.z) < 2.1 && Math.abs(other.x - r.x) < 0.8 && mayCollide(state, r.id, other.id)) {
        const side = Math.sign(r.x - other.x) || 1;
        impact(state, r, 7, side * 0.35);
        impact(state, other, 7, -side * 0.35);
        state.events.push({ type: "hit", actor: r.id, text: "CONTATO!" });
      }
    }
  }
}
function resolvePedestrians(state, oldZ) {
  for (const r of state.riders) {
    if (!r.recovery || r.out) continue;
    for (const t of state.traffic) {
      const now = t.z - r.z, before = t.z - t.speed * STEP - (oldZ.get(r.id) ?? r.z);
      if ((Math.abs(now) < trafficShape(state.trackId, t.kind).length || before * now < 0) && Math.abs(t.x - r.x) < trafficShape(state.trackId, t.kind).contact) {
        if (mayCollide(state, r.id, t.id, 1.4)) hitPedestrian(state, r, t.id, t.speed, r.x - t.x);
      }
    }
    for (const other of state.riders) {
      if (other.id === r.id || other.out || other.recovery || other.crash || other.finishedAt !== null || other.jumpTime > 0 || other.speed < 6) continue;
      const now = other.z - r.z, before = (oldZ.get(other.id) ?? other.z) - (oldZ.get(r.id) ?? r.z);
      if ((Math.abs(now) < 1.6 || before * now < 0) && Math.abs(other.x - r.x) < 1 && mayCollide(state, r.id, other.id, 1.4)) {
        if (hitPedestrian(state, r, other.id, other.speed, r.x - other.x)) {
          other.speed *= 0.92;
          other.hits++;
        }
      }
    }
  }
}
function createMultiplayerRace(trackId, players, seed = 88117, fillBots = false, condition = "sunset") {
  if (players.length < 2 || players.length > 8 || new Set(players.map((p) => p.id)).size !== players.length) throw new Error("A corrida precisa de 2 a 8 pilotos distintos.");
  const state = createRace(trackId, void 0, seed, condition);
  const colors = ["#dcff74", "#d87bfa", "#6cdace", "#f28451", "#ebbc5c", "#a4bde2", "#ef6f8a", "#e7e6dc"];
  const base = state.riders[0];
  const bots = state.riders.slice(1);
  const grid = trackId === "terra" ? [2.1, -2.1] : [-5.1, -1.7, 1.7, 5.1];
  state.riders = players.map((p, i) => ({ ...base, ...stockBike(p.bikeId), helmetId: getHelmet(p.helmetId).id, helmetColorId: getHelmetColor(p.helmetColorId).id, weaponId: getWeapon(p.weaponId)?.id, kneePadId: getKneePad(p.kneePadId)?.id, nitro: nitroCount(p.bikeId, p.nitro), id: p.id, name: p.name, color: colors[i], x: grid[i % grid.length], z: -(Math.floor(i / grid.length) * (trackId === "terra" ? 10 : 8)), profile: "player" }));
  if (fillBots) for (let i = players.length; i < 8; i++) {
    const bot = bots[i - players.length];
    const bike = BIKES[i % BIKES.length], pad = rivalKneePad(bike.id, bot.profile, getTrack(trackId).level);
    state.riders.push({ ...base, ...stockBike(bike.id), ...pad ? { kneePadId: pad } : {}, helmetId: bot.helmetId, helmetColorId: bot.helmetColorId, id: `cpu-${i}`, name: `${bot.name} CPU`, profile: bot.profile, color: colors[i], x: grid[i % grid.length], targetX: grid[i % grid.length], z: -(Math.floor(i / grid.length) * (trackId === "terra" ? 10 : 8)) });
  }
  state.multiplayer = { humanIds: players.map((p) => p.id), results: {} };
  return state;
}
function finishRider(state, rider, reason, arrestCause) {
  if (state.multiplayer?.results[rider.id] || rider.out) return;
  cancelStunt(rider);
  rider.kneeTime = 0;
  rider.wetKneeTicks = 0;
  if (reason !== "finish") {
    rider.out = reason;
    rider.attack = null;
  }
  const place = ranking(state).findIndex((r) => r.id === rider.id) + 1;
  const result = {
    reason,
    ...reason === "caught" ? { arrestCause: arrestCause ?? "stopped" } : {},
    place,
    time: rider.finishedAt ?? state.time,
    reward: state.multiplayer ? 0 : reason === "finish" ? Math.round(getTrack(state.trackId).prize * ([1, 0.8, 0.64, 0.5, 0.4, 0.32, 0.25, 0.2][place - 1] ?? 0.2)) : 120,
    hits: rider.hits,
    falls: rider.falls
  };
  if (state.multiplayer) {
    state.multiplayer.results[rider.id] = result;
    if (state.mode !== "finished" && state.multiplayer.humanIds.every((id) => state.multiplayer.results[id])) {
      state.mode = "finished";
      for (const bot of state.riders) if (bot.profile !== "player" && bot.profile !== "police" && !state.multiplayer.results[bot.id]) {
        finishRider(state, bot, bot.finishedAt !== null ? "finish" : "timeout");
      }
    }
  } else if (rider.id === "player") {
    state.result = result;
    state.mode = "finished";
  }
  state.events.push({ type: "finish", actor: rider.id });
}
function arrestFallenRiders(state) {
  for (const p of state.riders) {
    if (p.profile === "police" || p.out || p.finishedAt !== null || p.crash <= 0 || p.recovery?.phase === "exploding") continue;
    const near = state.riders.some((r) => r.profile === "police" && !r.out && r.crash <= 0 && r.integrity > 0 && Math.hypot(r.z - p.z, r.x - p.x) <= FALL_ARREST_RADIUS);
    if (near) {
      p.capture = 3;
      if (p.id === "player") state.capture = 3;
      finishRider(state, p, "caught", "fall");
    }
  }
  return state.mode === "finished";
}
function stepRace(state, commands = {}) {
  state.events = [];
  if (state.mode === "finished") return;
  state.tick++;
  if (state.mode === "countdown") {
    state.countdown -= STEP;
    if (state.countdown <= 0) {
      state.countdown = 0;
      state.mode = "racing";
    }
    return;
  }
  state.time += STEP;
  if (arrestFallenRiders(state)) return;
  const player = state.riders[0];
  const oldOrder = ranking(state).map((r) => r.id);
  const oldZ = new Map(state.riders.map((r) => [r.id, r.z]));
  for (const r of state.riders) {
    applyCommand(state, r, commands[r.id] ?? (r.profile === "player" ? EMPTY_COMMAND : botCommand(state, r)));
    if (!r.out && !r.crash && r.finishedAt === null && (r.wetKneeTicks ?? 0) * STEP > WET_KNEE_LIMIT) {
      crashRider(state, r, true);
      state.events[state.events.length - 1].text = "JOELHO NO MOLHADO POR TEMPO DEMAIS \xB7 QUEDA!";
    }
  }
  const active = state.riders.filter((r) => r.profile !== "police" && !r.out && r.finishedAt === null);
  const back = Math.min(...active.map((r) => r.z), player.z);
  if (state.trackId === "porto") stopAtPortQueue(state.traffic, STEP);
  for (const t of state.traffic) {
    t.z += t.speed * STEP;
    if (!t.queued && t.z < back - 100) t.z += getTrack(state.trackId).distance + 1800;
  }
  for (const o of state.obstacles) if (o.motion) o.x = obstacleX(o, state.time);
  resolveAttacks(state);
  resolveCollisions(state, oldZ);
  resolvePedestrians(state, oldZ);
  if (arrestFallenRiders(state)) return;
  if (active.some((r) => r.profile === "player" && r.speed > 49)) state.heat = clamp(state.heat + STEP * 0.37, 0, 100);
  else state.heat = Math.max(0, state.heat - STEP * 0.15);
  const front = active.slice().sort((a, b) => b.z - a.z)[0];
  if (!state.policeActive && state.heat >= 48 && front && front.z > 1300) {
    const police = makeRider("police", "POL\xCDCIA", "police", "#e7e9e5", guardRailPosition(state.trackId, state.trackId === "terra" ? clamp(front.x + 1.5, -3, 3) : front.x + 1.5, front.z - 100), front.z - 100);
    police.bikeId = "estradeira";
    police.speed = 58;
    police.maxSpeed = POLICE_TOP_SPEED;
    police.acceleration = 16;
    police.weapon = true;
    state.riders.push(police);
    state.policeActive = true;
    state.events.push({ type: "police", actor: "police", text: "POL\xCDCIA NA ESTRADA \xB7 CUIDADO!" });
  }
  const officers = state.riders.filter((r) => r.profile === "police" && !r.crash && r.integrity > 0);
  const length = getTrack(state.trackId).distance;
  for (const r of state.riders) if (r.profile !== "police" && !r.out && !r.recovery && r.finishedAt === null && r.z >= length) {
    r.finishedAt = state.time - (r.z - length) / Math.max(0.1, r.speed);
    r.z = length;
  }
  for (const r of state.riders) {
    if (r.profile === "police" || r.out) continue;
    const previous = !state.multiplayer && r.id === "player" ? state.capture : r.capture ?? 0;
    r.capture = officers.some((c) => Math.abs(c.z - r.z) < 18 && Math.abs(c.x - r.x) < 4 && r.speed < 8) ? previous + STEP : Math.max(0, previous - STEP * 2);
    if (r.id === "player") state.capture = r.capture;
    if (r.finishedAt !== null) {
      if (state.multiplayer ? !state.multiplayer.results[r.id] : r.id === "player") finishRider(state, r, "finish");
    } else if (r.integrity <= 0 && (!r.recovery || r.recovery.phase === "exploding" && r.recovery.timer === 0)) finishRider(state, r, "wrecked");
    else if (r.capture >= 3 && r.recovery?.phase !== "exploding") finishRider(state, r, "caught");
    else if (state.multiplayer && state.time >= 360) finishRider(state, r, "timeout");
  }
  advanceScenicEvent(state);
  advanceBanter(state);
  for (const [index, r] of ranking(state).entries()) if (index < oldOrder.indexOf(r.id)) state.events.push({ type: "pass", actor: r.id });
  if (state.tick % 600 === 0) {
    for (const key of Object.keys(state.collisions)) if (state.time - state.collisions[key] > 5) delete state.collisions[key];
  }
}

// src/multiplayer/protocol.ts
var NET_VERSION = 14;
var MAX_PLAYERS = 8;
var ROOM_WAIT_MS = 6e4;
var PUBLIC_ROOM_WAIT_MS = 12e4;
var READY_WAIT_MS = 5e3;
var RECONNECT_MS = 15e3;
function cleanName(value) {
  return typeof value === "string" ? value.normalize("NFKC").replace(/[^\p{L}\p{N} _.-]/gu, "").trim().slice(0, 18) || "Piloto" : "Piloto";
}
function cleanCommand(value) {
  if (!value || typeof value !== "object") return null;
  const c = value;
  if (![c.throttle, c.brake, c.steer].every((n) => typeof n === "number" && Number.isFinite(n))) return null;
  if (c.attack !== null && !["punch", "kick", "weapon"].includes(c.attack)) return null;
  return { throttle: Math.max(0, Math.min(1, c.throttle)), brake: Math.max(0, Math.min(1, c.brake)), steer: Math.max(-1, Math.min(1, c.steer)), attack: c.attack };
}
function cleanAttacks(value) {
  if (value === void 0) return [];
  if (!Array.isArray(value) || value.length > 8) return null;
  let previous = 0;
  const attacks = [];
  for (const a of value) {
    if (!a || !Number.isSafeInteger(a.seq) || a.seq <= previous || !["punch", "kick", "weapon"].includes(a.kind)) return null;
    attacks.push({ seq: a.seq, kind: a.kind });
    previous = a.seq;
  }
  return attacks;
}
function cleanActions(value) {
  if (value === void 0) return [];
  if (!Array.isArray(value) || value.length > 8) return null;
  let previous = 0;
  const actions = [];
  for (const a of value) {
    if (!a || !Number.isSafeInteger(a.seq) || a.seq <= previous || !["kneeLeft", "kneeRight", "nitro", "horn", "taunt", "wheelie"].includes(a.kind)) return null;
    actions.push({ seq: a.seq, kind: a.kind });
    previous = a.seq;
  }
  return actions;
}

// server/room.ts
var import_node_crypto = require("node:crypto");
var inputKey = (member) => `${member.id}:${member.epoch}`;
var secret = () => (0, import_node_crypto.randomBytes)(24).toString("base64url");
function makeMember(name, now, bikeId, loadout) {
  const bike = getBike(typeof bikeId === "string" ? bikeId : void 0);
  return { id: `human-${(0, import_node_crypto.randomBytes)(8).toString("hex")}`, name: cleanName(name), bikeId: bike.id, helmetId: getHelmet(loadout?.helmetId).id, helmetColorId: getHelmetColor(loadout?.helmetColorId).id, weaponId: getWeapon(loadout?.weaponId)?.id, kneePadId: getKneePad(loadout?.kneePadId)?.id, nitro: nitroCount(bike.id, loadout?.nitro), ready: false, connected: true, token: secret(), epoch: secret(), lastSeen: now };
}
function makeRoom(code, trackId, member, now, fillBots = false, condition, isPublic = false) {
  if (!TRACKS.some((t) => t.id === trackId)) throw new Error("Estrada inv\xE1lida.");
  if (condition !== void 0 && !CONDITIONS.some((c) => c.id === condition)) throw new Error("Condi\xE7\xE3o inv\xE1lida.");
  return {
    code,
    public: isPublic === true,
    condition: raceCondition(condition),
    trackId,
    fillBots: fillBots === true,
    phase: "lobby",
    locked: false,
    deadline: now + (isPublic === true ? PUBLIC_ROOM_WAIT_MS : ROOM_WAIT_MS),
    revision: 0,
    members: [member],
    race: null,
    ack: {},
    attackAck: {},
    actionAck: {},
    updatedAt: now,
    createdAt: now,
    finishedAt: null
  };
}
function viewRoom(room, now) {
  return {
    code: room.code,
    public: room.public === true,
    condition: raceCondition(room.condition),
    trackId: room.trackId,
    fillBots: room.fillBots,
    phase: room.phase,
    locked: room.locked,
    deadline: room.deadline,
    revision: room.revision,
    serverNow: now,
    simulationAt: room.updatedAt,
    members: room.members.map(({ id, name, bikeId, helmetId, helmetColorId, weaponId, kneePadId, nitro, ready, connected }) => ({ id, name, bikeId, helmetId, helmetColorId, weaponId, kneePadId, nitro, ready, connected })),
    race: room.race,
    ack: room.ack,
    attackAck: room.attackAck,
    actionAck: room.actionAck
  };
}
function publicRoomView(room, now) {
  if (room.public !== true || room.phase !== "lobby" || room.locked || now - room.createdAt > 30 * 6e4) return null;
  const players = room.members.filter((m) => m.connected && now - m.lastSeen <= RECONNECT_MS).length;
  if (!players || players >= MAX_PLAYERS || players >= 2 && room.deadline !== null && room.deadline - now <= READY_WAIT_MS) return null;
  return { code: room.code, trackId: room.trackId, condition: raceCondition(room.condition), fillBots: room.fillBots, players, maxPlayers: MAX_PLAYERS, deadline: room.deadline !== null && room.deadline > now ? room.deadline : null };
}
function sortPublicRooms(rooms) {
  return rooms.sort((a, b) => b.players - a.players || (a.deadline ?? Infinity) - (b.deadline ?? Infinity) || a.code.localeCompare(b.code)).slice(0, 50);
}
function lobbyClock(room, now) {
  if (room.phase !== "lobby") return;
  const present = room.members.filter((p) => p.connected);
  if (present.length < 2) {
    if (room.locked) {
      room.locked = false;
      room.deadline = now + (room.public ? PUBLIC_ROOM_WAIT_MS : ROOM_WAIT_MS);
    }
    if (room.deadline !== null && now >= room.deadline) room.deadline = null;
    return;
  }
  if (room.deadline === null) room.deadline = now + (room.public ? PUBLIC_ROOM_WAIT_MS : ROOM_WAIT_MS);
  if (!room.locked && present.every((p) => p.ready)) room.deadline = Math.min(room.deadline, now + READY_WAIT_MS);
  if (room.deadline - now <= READY_WAIT_MS) room.locked = true;
  if (now < room.deadline) return;
  room.members = present;
  room.race = createMultiplayerRace(room.trackId, present, (0, import_node_crypto.randomBytes)(4).readUInt32LE(), room.fillBots, room.condition);
  room.race.mode = "racing";
  room.race.countdown = 0;
  room.phase = "racing";
  room.updatedAt = now;
  room.deadline = null;
}
function joinRoom(room, member, now) {
  lobbyClock(room, now);
  if (room.phase !== "lobby" || room.locked) throw new Error("A largada j\xE1 foi fechada. Entre em outra sala.");
  room.members = room.members.filter((p) => p.connected);
  if (room.members.length >= MAX_PLAYERS) throw new Error("Sala cheia: o limite \xE9 de 8 pessoas.");
  if (member.accountId && room.members.some((m) => m.accountId === member.accountId)) throw new Error("Esta conta j\xE1 est\xE1 na sala.");
  room.members.push(member);
  lobbyClock(room, now);
}
function setReady(room, id, epoch, ready, now) {
  const member = room.members.find((p) => p.id === id && p.epoch === epoch);
  if (!member?.connected || room.phase !== "lobby" || room.locked) return;
  member.ready = ready;
  member.lastSeen = now;
  lobbyClock(room, now);
}
function depart(room, id, epoch, now, explicit = false) {
  const member = room.members.find((p) => p.id === id && p.epoch === epoch);
  if (!member) return;
  member.connected = false;
  member.ready = false;
  member.lastSeen = now;
  if (explicit && room.race) {
    const rider = room.race.riders.find((r) => r.id === id);
    if (rider && !room.race.multiplayer.results[id]) finishRider(room.race, rider, "left");
  }
  if (explicit && room.phase === "lobby") room.members = room.members.filter((p) => p !== member);
  lobbyClock(room, now);
}
function pulseRoom(room, inputs, now) {
  for (const m of room.members) {
    const input = inputs[inputKey(m)];
    if (input && input.at > m.lastSeen) {
      m.lastSeen = input.at;
      m.connected = true;
    }
    if (now - m.lastSeen > RECONNECT_MS) {
      m.connected = false;
      m.ready = false;
    }
  }
  if (room.phase === "lobby") {
    lobbyClock(room, now);
    return;
  }
  if (!room.race || room.phase === "finished") return;
  for (const m of room.members) {
    if (!m.connected && now - m.lastSeen > RECONNECT_MS) {
      const r = room.race.riders.find((r2) => r2.id === m.id);
      if (r) finishRider(room.race, r, "left");
    }
  }
  const steps = Math.min(120, Math.max(0, Math.floor((now - room.updatedAt) / (STEP * 1e3))));
  const commands = {};
  for (const m of room.members) {
    const latest = inputs[inputKey(m)];
    const onFoot = !!room.race.riders.find((r) => r.id === m.id)?.recovery;
    commands[m.id] = m.connected && latest && now - latest.at < 500 ? latest.command : onFoot ? EMPTY_COMMAND : { ...EMPTY_COMMAND, brake: 1 };
    if (latest && steps > 0) room.ack[m.id] = latest.seq;
  }
  const events = room.race.events.filter((e) => e.tick !== void 0 && e.tick > room.race.tick - 60);
  for (let i = 0; i < steps; i++) {
    const tickCommands = { ...commands };
    const started = [];
    for (const m of room.members) {
      const latest = inputs[inputKey(m)], rider = room.race.riders.find((r) => r.id === m.id);
      if (!latest || !m.connected || now - latest.at >= 500 || !rider) continue;
      const ability = latest.actions?.find((a) => a.seq > (room.actionAck?.[m.id] ?? 0));
      if (ability) {
        (room.actionAck ??= {})[m.id] = ability.seq;
        tickCommands[m.id] = { ...tickCommands[m.id], action: ability.kind };
      }
      const action = latest.attacks?.find((a) => a.seq > (room.attackAck[m.id] ?? 0));
      if (!action) continue;
      if (rider.out || rider.crash || (rider.jumpTime ?? 0) > 0 || rider.finishedAt !== null || action.kind === "weapon" && !rider.weapon) {
        room.attackAck[m.id] = action.seq;
        continue;
      }
      if (rider.attack || rider.cooldown > STEP) continue;
      tickCommands[m.id] = { ...tickCommands[m.id], attack: action.kind };
      room.attackAck[m.id] = action.seq;
      started.push({ id: m.id, seq: action.seq });
    }
    stepRace(room.race, tickCommands);
    for (const a of started) {
      const rider = room.race.riders.find((r) => r.id === a.id);
      if (rider?.attack) rider.attack.id = a.seq;
    }
    events.push(...room.race.events.map((e) => ({ ...e, tick: room.race.tick })));
  }
  room.race.events = events.filter((e) => (e.tick ?? 0) > room.race.tick - 60).slice(-128);
  room.updatedAt += steps * STEP * 1e3;
  if (now - room.updatedAt > 2e3) room.updatedAt = now;
  if (room.race.mode === "finished") {
    room.phase = "finished";
    room.finishedAt = now;
  }
}

// server/store.ts
var import_ioredis = __toESM(require("ioredis"), 1);
var BusyRoom = class extends Error {
};
var clone = (value) => structuredClone(value);
var MemoryStore = class {
  shared = false;
  rooms = /* @__PURE__ */ new Map();
  inputs = /* @__PURE__ */ new Map();
  async create(room) {
    if (this.rooms.has(room.code)) return false;
    this.rooms.set(room.code, clone(room));
    return true;
  }
  async read(code) {
    return clone(this.rooms.get(code) ?? null);
  }
  async publicRooms(now) {
    return sortPublicRooms([...this.rooms.values()].flatMap((r) => {
      const view = publicRoomView(r, now);
      return view ? [view] : [];
    }));
  }
  async mutate(code, change, _retries, localInputs = {}) {
    const old = this.rooms.get(code);
    if (!old) throw new Error("Sala n\xE3o encontrada ou encerrada.");
    const all = this.inputs.get(code) ?? {};
    for (const [key, input] of Object.entries(localInputs)) if (!all[key] || all[key].seq < input.seq) all[key] = clone(input);
    this.inputs.set(code, all);
    const room = clone(old);
    change(room, clone(this.inputs.get(code) ?? {}));
    room.revision++;
    this.rooms.set(code, room);
    return clone(room);
  }
  async input(code, key, input) {
    const all = this.inputs.get(code) ?? {};
    if (!all[key] || all[key].seq < input.seq) all[key] = clone(input);
    this.inputs.set(code, all);
  }
  async close() {
    this.rooms.clear();
    this.inputs.clear();
  }
  sweep(now) {
    for (const [id, r] of this.rooms) if (now - r.createdAt > 30 * 6e4) {
      this.rooms.delete(id);
      this.inputs.delete(id);
    }
  }
};
var unquote = (s) => (s ?? "").trim().replace(/^['"]|['"]$/g, "");
var RedisStore = class {
  shared = true;
  command;
  redis;
  constructor(options) {
    if (options.url) {
      this.redis = new import_ioredis.default(options.url, { lazyConnect: true, maxRetriesPerRequest: 1, connectTimeout: 4e3, enableOfflineQueue: true });
      this.redis.on("error", () => {
      });
      this.command = (...args) => this.redis.call(args[0], ...args.slice(1));
    } else if (options.restUrl && options.token) {
      this.command = async (...args) => {
        const response = await fetch(options.restUrl, { method: "POST", headers: { Authorization: `Bearer ${options.token}`, "Content-Type": "application/json" }, body: JSON.stringify(args), signal: AbortSignal.timeout(4e3) });
        if (!response.ok) throw new Error("N\xE3o foi poss\xEDvel acessar as salas.");
        const data = await response.json();
        if (data.error) throw new Error("O armazenamento das salas n\xE3o respondeu.");
        return data.result;
      };
    } else throw new Error("Configure o Redis do multiplayer no servidor.");
  }
  key(code, field) {
    return `asfalto:online:v${NET_VERSION}:{${code}}:${field}`;
  }
  publicIndex = `asfalto:online:v${NET_VERSION}:public-lobbies`;
  async create(room) {
    if (await this.command("SET", this.key(room.code, "state"), JSON.stringify(room), "NX", "EX", 1800) !== "OK") return false;
    if (room.public === true) await this.command("ZADD", this.publicIndex, room.createdAt, room.code);
    return true;
  }
  async read(code) {
    const raw = await this.command("GET", this.key(code, "state"));
    return raw ? JSON.parse(raw) : null;
  }
  async publicRooms(now) {
    await this.command("ZREMRANGEBYSCORE", this.publicIndex, "-inf", now - 30 * 6e4);
    const codes = await this.command("ZRANGE", this.publicIndex, 0, 511);
    const views = [];
    for (let i = 0; i < codes.length; i += 16) {
      const rooms = await Promise.all(codes.slice(i, i + 16).map((code) => this.read(code)));
      const stale = [];
      rooms.forEach((room, j) => {
        if (!room || room.phase !== "lobby" || room.public !== true) stale.push(codes[i + j]);
        if (room) {
          const view = publicRoomView(room, now);
          if (view) views.push(view);
        }
      });
      if (stale.length) await this.command("ZREM", this.publicIndex, ...stale);
    }
    return sortPublicRooms(views);
  }
  async input(code, key, input) {
    await this.command("EVAL", `local old=redis.call('HGET',KEYS[1],ARGV[1]); if not old or cjson.decode(old).seq<tonumber(ARGV[2]) then redis.call('HSET',KEYS[1],ARGV[1],ARGV[3]); redis.call('EXPIRE',KEYS[1],1800); return 1 end; return 0`, 1, this.key(code, "inputs"), key, input.seq, JSON.stringify(input));
  }
  async mutate(code, change, retries = 50, localInputs = {}) {
    const lock = this.key(code, "lock"), token = secret();
    let snapshot;
    for (let n = 0; n <= retries; n++) {
      const result = await this.command("EVAL", `
        if not redis.call('SET',KEYS[1],ARGV[1],'NX','PX',4000) then return {0} end
        local room=redis.call('GET',KEYS[2])
        if not room then redis.call('DEL',KEYS[1]); return {-1} end
        for key,raw in pairs(cjson.decode(ARGV[2])) do
          local input=cjson.decode(raw)
          local old=redis.call('HGET',KEYS[3],key)
          if not old or cjson.decode(old).seq<input.seq then redis.call('HSET',KEYS[3],key,raw) end
        end
        redis.call('EXPIRE',KEYS[3],1800)
        return {1,room,redis.call('HGETALL',KEYS[3])}
      `, 3, lock, this.key(code, "state"), this.key(code, "inputs"), token, JSON.stringify(Object.fromEntries(Object.entries(localInputs).map(([key, input]) => [key, JSON.stringify(input)]))));
      if (result[0] === -1) throw new Error("Sala n\xE3o encontrada ou encerrada.");
      if (result[0] === 1) {
        snapshot = result;
        break;
      }
      if (n < retries) await new Promise((resolve) => setTimeout(resolve, 20));
    }
    if (!snapshot) throw new BusyRoom("Sala ocupada por um instante. Tente novamente.");
    let committed = false;
    try {
      const room = JSON.parse(snapshot[1]), entries = snapshot[2], inputs = {};
      for (let i = 0; i < entries.length; i += 2) inputs[entries[i]] = JSON.parse(entries[i + 1]);
      change(room, inputs);
      room.revision++;
      const saved = await this.command("EVAL", `if redis.call('GET',KEYS[1])==ARGV[1] then redis.call('SET',KEYS[2],ARGV[2],'EX',1800); redis.call('DEL',KEYS[1]); return 1 end; return 0`, 2, lock, this.key(code, "state"), token, JSON.stringify(room));
      if (saved !== 1) throw new BusyRoom("A sala est\xE1 sincronizando. Tente novamente.");
      committed = true;
      return room;
    } finally {
      if (!committed) await this.command("EVAL", `if redis.call('GET',KEYS[1])==ARGV[1] then return redis.call('DEL',KEYS[1]) end; return 0`, 1, lock, token).catch(() => {
      });
    }
  }
  async close() {
    this.redis?.disconnect();
  }
};
function storeFromEnvironment(env = process.env) {
  const mode = unquote(env.ASFALTO_STORE).toLowerCase();
  if (mode && mode !== "memory" && mode !== "redis") throw new Error("ASFALTO_STORE deve ser memory ou redis.");
  if (mode === "memory") {
    if (env.VERCEL) throw new Error("O modo memory exige um \xFAnico servidor persistente, fora do Vercel.");
    return new MemoryStore();
  }
  const url = unquote(env.ASFALTO_REDIS_URL || env.REDIS_URL || env.KV_URL);
  const restUrl = unquote(env.KV_REST_API_URL || env.UPSTASH_REDIS_REST_URL);
  const token = unquote(env.KV_REST_API_TOKEN || env.UPSTASH_REDIS_REST_TOKEN);
  if (url || restUrl && token) return new RedisStore({ url, restUrl, token });
  if (mode === "redis" || env.VERCEL || env.NODE_ENV === "production") throw new Error("Configure o Redis ou selecione ASFALTO_STORE=memory em uma VPS com um \xFAnico processo.");
  return new MemoryStore();
}

// server/service.ts
function createGameServer(store, options = {}) {
  const now = options.now ?? Date.now;
  const peers = /* @__PURE__ */ new Set();
  const revisions = /* @__PURE__ */ new Map();
  const pumping = /* @__PURE__ */ new Set();
  const latest = /* @__PURE__ */ new Map();
  const limits = /* @__PURE__ */ new Map();
  let discovery;
  const server2 = (0, import_node_http.createServer)(async (req, res) => {
    res.setHeader("Cache-Control", "no-store");
    res.setHeader("Content-Type", "application/json");
    if (options.accounts && await options.accounts.handle(req, res)) return;
    const query = (req.url ?? "").split("?").slice(1).join("?");
    if (new URLSearchParams(query).get("op") === "rooms") {
      if (req.method !== "GET") {
        res.writeHead(405, { Allow: "GET" });
        res.end(JSON.stringify({ error: "Use GET para encontrar salas." }));
        return;
      }
      const origin = req.headers.origin;
      if (origin && options.origins?.includes(origin)) {
        res.setHeader("Access-Control-Allow-Origin", origin);
        res.setHeader("Vary", "Origin");
      }
      try {
        if (!discovery || now() - discovery.at >= 1e3) discovery = { at: now(), pending: store.publicRooms(now()) };
        const rooms = await discovery.pending;
        res.end(JSON.stringify({ rooms, serverNow: now(), version: NET_VERSION }));
      } catch {
        discovery = void 0;
        res.statusCode = 503;
        res.end(JSON.stringify({ error: "N\xE3o foi poss\xEDvel buscar salas. Tente atualizar a lista." }));
      }
      return;
    }
    res.statusCode = 200;
    res.end(JSON.stringify({ service: "asfalto-bruto", appVersion: GAME_VERSION, version: NET_VERSION, multiplayer: true, sharedRooms: store.shared, storage: store.shared ? "redis" : "memory", region: process.env.VERCEL_REGION ?? "local", activeRaces: [...latest.values()].filter((r) => r.phase === "racing" && [...peers].some((p) => p.code === r.code)).length }));
  });
  const wss = new import_ws.WebSocketServer({ noServer: true, maxPayload: 4096, perMessageDeflate: false });
  server2.on("upgrade", (req, socket, head) => {
    const origin = req.headers.origin;
    const host = req.headers["x-forwarded-host"] || req.headers.host;
    const allowed = !origin || origin === `https://${host}` || origin === `http://${host}` || options.origins?.includes(origin);
    if (!allowed || peers.size >= 256) {
      socket.write("HTTP/1.1 403 Forbidden\r\n\r\n");
      socket.destroy();
      return;
    }
    const remote = req.socket.remoteAddress ?? "unknown", forwarded = req.headers["x-real-ip"];
    const localProxy = options.trustLoopbackProxy && ["127.0.0.1", "::1", "::ffff:127.0.0.1"].includes(remote);
    const ip = localProxy && typeof forwarded === "string" && (0, import_node_net.isIP)(forwarded) ? forwarded : remote;
    const limit = limits.get(ip) ?? { at: now(), count: 0 };
    if (now() - limit.at > 6e4) {
      limit.at = now();
      limit.count = 0;
    }
    limits.set(ip, limit);
    if (++limit.count > 80) {
      socket.write("HTTP/1.1 429 Too Many Requests\r\n\r\n");
      socket.destroy();
      return;
    }
    wss.handleUpgrade(req, socket, head, (ws) => wss.emit("connection", ws, req));
  });
  function send(peer, message) {
    if (peer.ws.readyState !== import_ws.WebSocket.OPEN) return;
    if (peer.ws.bufferedAmount > 512e3) {
      peer.ws.close(1013, "Conex\xE3o lenta");
      return;
    }
    peer.ws.send(JSON.stringify(message));
  }
  function broadcast(room) {
    const previous = latest.get(room.code);
    for (const member of previous?.members ?? []) if (!room.members.some((m) => m.id === member.id)) options.accounts?.economy.releaseMember(member, previous?.race?.riders.find((r) => r.id === member.id)?.nitroUsed ?? 0);
    latest.set(room.code, room);
    try {
      options.accounts?.recordRoom(room);
    } catch {
      console.error("Falha ao gravar resultado no ranking; ser\xE1 tentado novamente.");
    }
    if ((revisions.get(room.code) ?? -1) >= room.revision) return;
    revisions.set(room.code, room.revision);
    const message = { type: "state", room: viewRoom(room, now()) };
    for (const peer of peers) if (peer.code === room.code) send(peer, message);
  }
  async function flush(peer) {
    if (peer.writing || !peer.code) return;
    peer.writing = true;
    try {
      while (peer.pending && peer.code) {
        const pending = peer.pending;
        peer.pending = void 0;
        await store.input(peer.code, `${peer.id}:${peer.epoch}`, pending);
      }
    } catch {
      send(peer, { type: "error", message: "A conex\xE3o com a sala est\xE1 inst\xE1vel. Reconectando\u2026" });
      peer.ws.close(1013);
    } finally {
      peer.writing = false;
    }
  }
  async function attach(peer, room, member) {
    if (peer.ws.readyState !== import_ws.WebSocket.OPEN) {
      await store.mutate(room.code, (r) => depart(r, member.id, member.epoch, now(), true)).then(broadcast).catch(() => {
      });
      options.accounts?.economy.releaseMember(member);
      return;
    }
    peer.code = room.code;
    peer.id = member.id;
    peer.epoch = member.epoch;
    peer.seq = room.ack[member.id] ?? 0;
    send(peer, { type: "welcome", id: member.id, token: member.token, room: viewRoom(room, now()) });
    broadcast(room);
  }
  wss.on("connection", (ws, req) => {
    const peer = { ws, code: "", id: "", epoch: "", seq: 0, writing: false, lastSeen: now(), alive: true };
    peers.add(peer);
    let busy = false, messages = 0, windowStart = now();
    ws.on("pong", () => {
      peer.alive = true;
      peer.lastSeen = now();
    });
    ws.on("message", async (raw) => {
      if (now() - windowStart > 1e3) {
        messages = 0;
        windowStart = now();
      }
      if (++messages > 100) {
        ws.close(1008, "Muitas mensagens");
        return;
      }
      let data;
      try {
        data = JSON.parse(raw.toString());
      } catch {
        send(peer, { type: "error", message: "Mensagem inv\xE1lida." });
        return;
      }
      if (!data || typeof data !== "object") return;
      peer.lastSeen = now();
      if (data.type === "ping") {
        send(peer, { type: "pong", sentAt: Number(data.sentAt) || 0, serverNow: now() });
        return;
      }
      if (data.type === "input") {
        const command = cleanCommand(data.command), attacks = cleanAttacks(data.attacks), actions = cleanActions(data.actions);
        if (!peer.code || !command || !attacks || !actions || !Number.isSafeInteger(data.seq) || data.seq <= peer.seq) return;
        peer.seq = data.seq;
        peer.pending = peer.latestInput = { seq: data.seq, command, attacks, actions, at: now() };
        void flush(peer);
        return;
      }
      if (busy) return;
      busy = true;
      let reservation;
      try {
        if (["create", "join", "resume"].includes(data.type)) {
          if (peer.code) throw new Error("Voc\xEA j\xE1 est\xE1 em uma sala.");
          if (data.version !== NET_VERSION) throw new Error("Atualize a p\xE1gina para entrar nesta vers\xE3o.");
          if (data.type === "create") {
            const member = makeMember(data.name, now(), data.bikeId, data.loadout);
            member.accountId = options.accounts?.identity(req)?.account.id;
            let room;
            options.accounts?.economy.equipMember(member.accountId, member);
            reservation = member;
            do {
              room = makeRoom((0, import_node_crypto2.randomBytes)(4).toString("hex").slice(0, 6).toUpperCase(), data.trackId, member, now(), data.fillBots === true, data.condition, data.public === true);
            } while (!await store.create(room));
            await attach(peer, room, member);
          } else {
            const code = String(data.code ?? "").toUpperCase();
            if (!/^[A-F0-9]{6}$/.test(code)) throw new Error("Digite o c\xF3digo de 6 caracteres da sala.");
            let member = makeMember(data.name, now(), data.bikeId, data.loadout);
            member.accountId = options.accounts?.identity(req)?.account.id;
            if (data.type === "join") {
              options.accounts?.economy.equipMember(member.accountId, member);
              reservation = member;
            }
            const room = await store.mutate(code, (r) => {
              if (data.type === "join") {
                if (data.publicOnly === true && !publicRoomView(r, now())) throw new Error("Esta sala n\xE3o est\xE1 mais dispon\xEDvel. Atualize a lista e escolha outra.");
                joinRoom(r, member, now());
              } else {
                const found = r.members.find((m) => typeof data.token === "string" && m.token === data.token);
                if (found?.accountId && found.accountId !== options.accounts?.identity(req)?.account.id) throw new Error("Entre na mesma conta para retomar esta corrida.");
                if (!found || now() - found.lastSeen > RECONNECT_MS && r.phase === "lobby") throw new Error("Sua vaga expirou. Entre novamente.");
                if (r.race && now() - found.lastSeen > RECONNECT_MS) {
                  const rider = r.race.riders.find((p) => p.id === found.id);
                  if (rider) finishRider(r.race, rider, "left");
                }
                found.connected = true;
                found.lastSeen = now();
                found.epoch = secret();
                member = found;
                lobbyClock(r, now());
              }
            });
            await attach(peer, room, member);
          }
        } else if (data.type === "ready" && peer.code && typeof data.ready === "boolean") {
          broadcast(await store.mutate(peer.code, (r) => setReady(r, peer.id, peer.epoch, data.ready, now())));
        } else if (data.type === "leave" && peer.code) {
          const code = peer.code;
          peer.code = "";
          peer.pending = void 0;
          broadcast(await store.mutate(code, (r) => depart(r, peer.id, peer.epoch, now(), true)));
          send(peer, { type: "left" });
        }
      } catch (error) {
        if (reservation && !peer.code) options.accounts?.economy.releaseMember(reservation);
        const message = error instanceof Error && !(error instanceof TypeError) ? error.message : "N\xE3o foi poss\xEDvel entrar na sala.";
        const fatal = data.type === "resume" && /vaga expirou|não encontrada|Atualize/.test(message);
        send(peer, { type: "error", message, fatal });
        if (data.type === "resume" && !fatal) peer.ws.close(1013);
      } finally {
        busy = false;
      }
    });
    ws.on("close", () => {
      peers.delete(peer);
      peer.pending = void 0;
      if (peer.code) void store.mutate(peer.code, (r) => depart(r, peer.id, peer.epoch, now())).then(broadcast).catch(() => {
      });
    });
    ws.on("error", () => {
    });
  });
  async function pump(code) {
    if (pumping.has(code)) return;
    pumping.add(code);
    try {
      const inputs = {};
      for (const p of peers) if (p.code === code && p.latestInput) inputs[`${p.id}:${p.epoch}`] = p.latestInput;
      broadcast(await store.mutate(code, (r, inputs2) => pulseRoom(r, inputs2, now()), 0, inputs));
    } catch (e) {
      if (e instanceof BusyRoom) {
        const room = await store.read(code).catch(() => null);
        if (room) broadcast(room);
      } else for (const peer of peers) if (peer.code === code) {
        send(peer, { type: "error", message: "N\xE3o foi poss\xEDvel sincronizar a sala. Reconectando\u2026" });
        peer.ws.close(1013);
      }
    } finally {
      pumping.delete(code);
    }
  }
  let cycles = 0;
  const timer = setInterval(() => {
    cycles++;
    for (const peer of peers) void flush(peer);
    const codes = new Set([...peers].map((p) => p.code).filter(Boolean));
    for (const code of codes) if (latest.get(code)?.phase === "racing" || latest.get(code)?.locked || cycles % 10 === 0) void pump(code);
    if (cycles % 100 === 0) {
      for (const peer of peers) {
        if (!peer.alive || !peer.code && now() - peer.lastSeen > 2e4) {
          peer.ws.terminate();
          continue;
        }
        peer.alive = false;
        peer.ws.ping();
        if (peer.code && latest.get(peer.code)?.phase === "lobby") void store.mutate(peer.code, (r) => {
          const m = r.members.find((m2) => m2.id === peer.id && m2.epoch === peer.epoch);
          if (m) {
            m.lastSeen = now();
            m.connected = true;
          }
        }).then(broadcast).catch(() => {
        });
      }
      for (const [code, room] of latest) if (!codes.has(code) && room.members.every((m) => now() - m.lastSeen > RECONNECT_MS)) {
        void store.mutate(code, (r) => {
          for (const m of [...r.members]) depart(r, m.id, m.epoch, now(), true);
        }).then((r) => {
          broadcast(r);
          for (const m of room.members) options.accounts?.economy.releaseMember(m, r.race?.riders.find((p) => p.id === m.id)?.nitroUsed ?? 0);
          latest.delete(code);
          revisions.delete(code);
        }).catch(() => {
        });
      }
      for (const [ip, l] of limits) if (now() - l.at > 6e4) limits.delete(ip);
      if (store instanceof MemoryStore) store.sweep(now());
    }
  }, 50);
  timer.unref();
  return { server: server2, wss, async close() {
    clearInterval(timer);
    for (const p of peers) p.ws.terminate();
    await new Promise((resolve) => wss.close(() => resolve()));
    await new Promise((resolve) => server2.close(() => resolve()));
    await store.close();
  } };
}

// api/asfalto.ts
var server;
try {
  server = createGameServer(storeFromEnvironment()).server;
} catch {
  server = (0, import_node_http2.createServer)((_req, res) => {
    res.writeHead(503, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "Multiplayer indispon\xEDvel: configure o Redis no Vercel. O modo individual continua dispon\xEDvel." }));
  });
}
var asfalto_default = server;
module.exports = module.exports.default;
